'use strict';
(()=>{let session={authenticated:false},published=null;const MODE='pixely-developer-mode';let enabled=sessionStorage.getItem(MODE)==='1';
async function request(action,body){const r=await fetch('/api/content?action='+action,{method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json','x-pixely-request':'1',...(session.csrf?{'x-pixely-csrf':session.csrf}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});let data;try{data=await r.json();}catch{throw Error('서버 응답을 읽지 못했어요');}if(!r.ok)throw Error(data.error||'저장하지 못했어요');return data;}
function setMode(value){enabled=value&&session.authenticated;sessionStorage.setItem(MODE,enabled?'1':'0');dispatchEvent(new CustomEvent('pixely:developer-mode',{detail:{enabled}}));refresh();}
const isEditor=()=>session.authenticated&&enabled;
function refresh(){document.querySelectorAll('[data-developer-login]').forEach(b=>b.textContent=isEditor()?'개발자 모드 켜짐':'개발자 모드');}
let login;function dialog(){if(login)return login;login=document.createElement('dialog');login.className='developer-login';login.innerHTML='<form><h2>개발자 모드</h2><p>제작자 로그인 코드를 입력해 주세요</p><label>로그인 코드<input type="password" name="code" autocomplete="current-password" required maxlength="200"></label><p role="status" class="login-status"></p><div><button type="button" data-cancel>취소</button><button type="submit">로그인</button></div></form>';document.body.append(login);login.querySelector('[data-cancel]').onclick=()=>login.close();login.querySelector('form').onsubmit=async e=>{e.preventDefault();const submit=login.querySelector('[type=submit]'),status=login.querySelector('.login-status');submit.disabled=true;try{session={...session,...await request('login',{code:login.querySelector('input').value})};login.querySelector('input').value='';setMode(true);login.close();}catch(err){status.textContent=err.message;}finally{submit.disabled=false;}};return login;}
async function loginOpen(){await ready;if(session.authenticated){setMode(!enabled);return;}const d=dialog();d.querySelector('.login-status').textContent=session.configured===false?'서버 로그인 설정을 확인해 주세요':'';d.showModal();d.querySelector('input').focus();}
const ready=(async()=>{try{session=await request('session');published=await request('published');}catch(e){session.error=e.message;}if(!session.authenticated)enabled=false;refresh();return session;})();
async function upload(image){if(image.path)return image;if(!(image.blob instanceof Blob))throw Error('업로드할 이미지가 없어요');const ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/gif':'gif'}[image.blob.type];if(!ext)throw Error('지원하지 않는 이미지예요');const result=await window.PixelyUpload.send(session.scope+'/images/'+crypto.randomUUID()+'.'+ext,image.blob,session.csrf);return {path:result.pathname,transform:image.transform};}
async function prepare(content,images){const assets={};for(const [key,image]of images){assets[key]=await upload(image);}return {...content,assets};}
async function save(content,baseRevision){if(!isEditor())throw Error('개발자 모드를 켜 주세요');return request('save',{content,baseRevision});}
async function publish(baseRevision){if(!isEditor())throw Error('개발자 모드를 켜 주세요');published=await request('publish',{baseRevision,publishedRevision:published?.revision||'initial'});return published;}
const imageURL=path=>'/api/image?path='+encodeURIComponent(path);
window.PixelyAdmin={ready,request,setMode,isEditor,loginOpen,upload,prepare,save,publish,imageURL,getSession:()=>({...session}),getPublished:()=>published,refreshPublished:async()=>published=await request('published')};
document.querySelectorAll('[data-developer-login]').forEach(b=>b.onclick=loginOpen);
})();
