'use strict';
(()=>{let session={authenticated:false},published=null;const MODE='pixely-developer-mode';let enabled=sessionStorage.getItem(MODE)==='1';
async function request(action,body){const r=await fetch('/api/content?action='+action,{method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json','x-pixely-request':'1',...(session.csrf?{'x-pixely-csrf':session.csrf}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});let data;try{data=await r.json();}catch{throw Error('서버 응답을 읽지 못했어요');}if(!r.ok)throw Error(data.error||'저장하지 못했어요');return data;}
function setMode(value){const next=!!(value&&session.authenticated);if(enabled===next){refresh();return;}enabled=next;sessionStorage.setItem(MODE,enabled?'1':'0');dispatchEvent(new CustomEvent('pixely:developer-mode',{detail:{enabled}}));refresh();}
const isEditor=()=>session.authenticated&&enabled;
let hub, switcher;const leaveHandlers=new Set();
function refresh(){document.querySelectorAll('[data-developer-login]').forEach(b=>b.textContent=isEditor()?'개발자 편집 메뉴':'개발자 모드');if(switcher)switcher.hidden=!isEditor();}
async function leave(url){for(const fn of leaveHandlers)await fn();location.href=url;}
function editorMenu(){
 if(!hub){hub=document.createElement('dialog');hub.className='developer-menu';hub.setAttribute('aria-labelledby','developer-menu-title');hub.innerHTML='<header><div><p>개발자 모드</p><h2 id="developer-menu-title">어디를 편집할까?</h2></div><button type="button" data-close aria-label="편집 메뉴 닫기">×</button></header><div class="developer-destinations"><button data-destination="./chapters.html?edit=1"><strong>챕터</strong><span>제목 · 소개 · 이미지</span></button><button data-destination="./collection.html?edit=1"><strong>콜렉션</strong><span>인물 · 카드 · 아이템 · 추억</span></button><button data-destination="./game.html?edit=1"><strong>플레이</strong><span>장소 · 캐릭터 · 대사 · 퍼즐</span></button></div><p class="developer-help">저장 → 미리보기 → 사이트에 반영</p><footer><span>테스트 진행은 일반 기록과 별도</span><button type="button" data-normal>일반 화면으로</button></footer><p role="status"></p>';document.body.append(hub);hub.querySelector('[data-close]').onclick=()=>hub.close();hub.querySelectorAll('[data-destination]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{setMode(true);await leave(b.dataset.destination);}catch(e){hub.querySelector('[role=status]').textContent=e.message;b.disabled=false;}});hub.querySelector('[data-normal]').onclick=normalView;}
 if(!hub.open)hub.showModal();
}
async function normalView(){try{for(const fn of leaveHandlers)await fn();setMode(false);if(hub?.open)hub.close();const url=new URL(location.href);url.searchParams.delete('edit');location.replace(url.pathname+url.search);}catch(e){if(hub)hub.querySelector('[role=status]').textContent=e.message;}}
function setupSwitcher(){switcher=document.createElement('div');switcher.className='developer-switcher';switcher.hidden=true;switcher.innerHTML='<span>개발자 모드</span><button type="button">편집 메뉴</button><button type="button">일반 화면</button>';const [menu,normal]=switcher.querySelectorAll('button');menu.onclick=editorMenu;normal.onclick=normalView;document.body.append(switcher);refresh();}

let login;function dialog(){if(login)return login;login=document.createElement('dialog');login.className='developer-login';login.innerHTML='<form><h2>개발자 모드</h2><p>제작자 로그인 코드를 입력해 주세요</p><label>로그인 코드<input type="password" name="code" autocomplete="current-password" required maxlength="200"></label><p role="status" class="login-status"></p><div><button type="button" data-cancel>취소</button><button type="submit">로그인</button></div></form>';document.body.append(login);login.querySelector('[data-cancel]').onclick=()=>login.close();login.querySelector('form').onsubmit=async e=>{e.preventDefault();const submit=login.querySelector('[type=submit]'),status=login.querySelector('.login-status');submit.disabled=true;try{session={...session,...await request('login',{code:login.querySelector('input').value})};login.querySelector('input').value='';setMode(true);login.close();editorMenu();}catch(err){status.textContent=err.message;}finally{submit.disabled=false;}};return login;}
async function loginOpen(){await ready;if(session.authenticated){setMode(true);editorMenu();return;}const d=dialog();d.querySelector('.login-status').textContent=session.configured===false?'서버 로그인 설정을 확인해 주세요':'';d.showModal();d.querySelector('input').focus();}
const ready=(async()=>{try{session=await request('session');published=await request('published');}catch(e){session.error=e.message;}if(!session.authenticated)enabled=false;setupSwitcher();refresh();return session;})();
async function upload(image){if(image.path)return image;if(!(image.blob instanceof Blob))throw Error('업로드할 이미지가 없어요');const audio=image.blob.type.startsWith('audio/');const ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/gif':'gif','audio/mpeg':'mp3','audio/ogg':'ogg','audio/wav':'wav','audio/x-wav':'wav','audio/mp4':'m4a'}[image.blob.type];if(!ext)throw Error('지원하지 않는 파일 형식이에요');const result=await window.PixelyUpload.send(session.scope+(audio?'/sounds/':'/images/')+crypto.randomUUID()+'.'+ext,image.blob,session.csrf);return audio?{path:result.pathname,name:image.name||'효과음'}:{path:result.pathname,transform:image.transform};}
async function prepare(content,images){const assets={},sounds={...(content.sounds||{})};for(const [key,image]of images){if(key.startsWith('sound:'))sounds[key]=await upload(image);else assets[key]=await upload(image);}return {...content,assets,sounds};}
async function save(content,baseRevision){if(!isEditor())throw Error('개발자 모드를 켜 주세요');return request('save',{content,baseRevision});}
async function publish(baseRevision){if(!isEditor())throw Error('개발자 모드를 켜 주세요');published=await request('publish',{baseRevision,publishedRevision:published?.revision||'initial'});return published;}
const imageURL=path=>'/api/image?path='+encodeURIComponent(path);
window.PixelyAdmin={ready,request,editorMenu,normalView,beforeLeave:fn=>{leaveHandlers.add(fn);return()=>leaveHandlers.delete(fn);},setMode,isEditor,loginOpen,upload,prepare,save,publish,imageURL,getSession:()=>({...session}),getPublished:()=>published,refreshPublished:async()=>published=await request('published')};
document.querySelectorAll('[data-developer-login]').forEach(b=>b.onclick=loginOpen);
})();
