'use strict';
(()=>{
const palettes={jam:{accent:'#79B7E2',soft:'#E8F4FC',text:'#68482F'},gak:{accent:'#E8B84B',soft:'#FFF2CF',text:'#68482F'},rad:{accent:'#D87575',soft:'#FBE8E8',text:'#68482F'},soo:{accent:'#A48ACC',soft:'#F1EAFB',text:'#68482F'},gong:{accent:'#78B98A',soft:'#E8F5EA',text:'#68482F'},duk:{accent:'#E7A263',soft:'#FFF0DF',text:'#68482F'},player:{accent:'#82B8AF',soft:'#ECF5EB',text:'#68482F'}};
const color=v=>typeof v==='string'&&/^#[a-f0-9]{6}$/i.test(v),id=v=>typeof v==='string'&&/^[a-z0-9][a-z0-9_-]{0,79}$/i.test(v)&&!['constructor','prototype','__proto__'].includes(v),clamp=(v,a,b,d)=>Number.isFinite(Number(v))?Math.min(b,Math.max(a,Number(v))):d;
function style(raw,key){const base=palettes[key]||palettes.player;const r={...base,...(raw||{})};for(const k of ['accent','soft','text'])if(!color(r[k]))throw Error('캐릭터 자막 색상을 확인해 주세요');return {accent:r.accent,soft:r.soft,text:r.text};}
function character(data,line){return data.characters.find(c=>c.id===line.actor)||data.characters.find(c=>line.speaker===c.name||line.speaker?.startsWith(c.name+' ·'));}
function caption(raw){if(raw===undefined||raw===null||raw.enabled===false)return null;if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('말풍선 설정을 확인해 주세요');const c=structuredClone(raw);if(typeof c.text!=='string'||c.text.length>120)throw Error('강조 문구는 120자 이하로 적어 주세요');c.kind||='bubble';c.animation||='fade';if(!['bubble','thought','surprise','quiet','subtitle'].includes(c.kind)||!['none','fade','pop'].includes(c.animation))throw Error('말풍선 종류와 애니메이션을 확인해 주세요');if(c.actor&&!id(c.actor))throw Error('말풍선 캐릭터를 확인해 주세요');if(c.sound&&!/^sound:[a-z0-9_-]{1,100}$/i.test(c.sound))throw Error('자막 효과음 연결을 확인해 주세요');for(const key of ['textColor','borderColor','background'])if(c[key]&&!color(c[key]))throw Error('말풍선 색상을 확인해 주세요');c.enabled=true;c.position=c.position==='manual'?'manual':'auto';c.x=clamp(c.x,0,100,50);c.y=clamp(c.y,0,100,24);c.size=clamp(c.size,18,48,c.kind==='quiet'?22:28);c.duration=clamp(c.duration,500,15000,2500);c.delay=clamp(c.delay,0,5000,0);c.persist=c.persist===true;c.order=c.order==='back'?'back':'front';return c;}
function line(raw){if(!raw||typeof raw!=='object'||typeof raw.text!=='string'||raw.text.length>8000)throw Error('대사·독백은 한 줄에 8000자 이하로 적어 주세요');if(raw.speaker!==undefined&&(typeof raw.speaker!=='string'||raw.speaker.length>100))throw Error('화자 이름은 100자 이하로 적어 주세요');if(raw.actor!==undefined&&raw.actor!==''&&!id(raw.actor))throw Error('화자를 확인해 주세요');if(raw.delivery!==undefined&&!['dialogue','monologue','reaction'].includes(raw.delivery))throw Error('대사 표시 방식을 확인해 주세요');const out=structuredClone(raw);if(raw.caption!==undefined)out.caption=caption(raw.caption);return out;}
// Each range refers to the original text; joining pages must recover every character.
function paginate(text,width,lines,measure){width=Math.max(20,width);lines=Math.max(1,Math.floor(lines));let start=0,index=0,row=1,rowWidth=0;const pages=[];for(const ch of text){if(ch==='\n'){if(row>=lines){pages.push({start,end:index+ch.length});start=index+ch.length;row=1;}else row++;rowWidth=0;}else{const w=measure(ch);if(rowWidth+w>width&&rowWidth>0){if(row>=lines){pages.push({start,end:index});start=index;row=1;}else row++;rowWidth=0;}rowWidth+=w;}index+=ch.length;}if(start<text.length||!pages.length)pages.push({start,end:text.length});return pages;}
function place({x,y,w,h,width,height,bottom,faces=[],objects=[],manual=false}){const pad=width*.02,maxY=Math.max(pad,bottom-h-pad),bound=(a,b)=>({x:clamp(a,pad,Math.max(pad,width-w-pad),pad),y:clamp(b,pad,maxY,pad)});const preferred=bound(x-w/2,y-h/2);if(manual)return preferred;const overlap=(a,b)=>Math.max(0,Math.min(a.x+w,b.x+b.w)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+h,b.y+b.h)-Math.max(a.y,b.y));const candidates=[preferred,...faces.flatMap(f=>[bound(f.x+(f.w-w)/2,f.y-h-pad),bound(f.x-w-pad,f.y),bound(f.x+f.w+pad,f.y)])];return candidates.reduce((best,p)=>{const score=faces.reduce((n,f)=>n+overlap(p,f)*100,0)+objects.reduce((n,o)=>n+overlap(p,o),0)+Math.hypot(p.x-preferred.x,p.y-preferred.y);return !best||score<best.score?{...p,score}:best;},null);}
function parseSequence(text,characters,fallback={speaker:'꿈뜰이',actor:'player',delivery:'dialogue'}){const rows=[];for(const part of text.split('\n')){const match=part.match(/^\s*([^:：]{1,30})[:：]\s*(.*)$/),character=match&&characters.find(c=>c.name===match[1].trim());if(character)rows.push({type:'say',speaker:character.name,actor:character.id,delivery:character.id==='player'?fallback.delivery:'dialogue',text:match[2]});else if(rows.length)rows.at(-1).text+='\n'+part;else rows.push({type:'say',...fallback,text:part});}return rows.filter(r=>r.text.trim()).map(line);}
const api={parseSequence,palettes,style,character,caption,line,paginate,place,clamp};if(typeof module!=='undefined'&&module.exports)module.exports=api;else window.PixelyDialogue=api;
})();
