'use strict';
(()=>{const DB='pixely-adventure-game';let connection;function open(){if(connection)return Promise.resolve(connection);return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{r.result.createObjectStore('slots');r.result.createObjectStore('autosaves');r.result.createObjectStore('metadata');};r.onerror=()=>no(r.error);r.onblocked=()=>no(Error('다른 게임 탭을 닫고 다시 시도해 주세요'));r.onsuccess=()=>{connection=r.result;connection.onversionchange=()=>{connection.close();connection=null;};ok(connection);};});}async function tx(names,mode,work){const db=await open();return new Promise((ok,no)=>{const t=db.transaction(names,mode);let value;t.oncomplete=()=>{try{ok(typeof value==='function'?value():value);}catch(e){no(e);}};t.onabort=()=>no(t.error||Error('저장하지 못했어요'));try{value=work(t);}catch(e){t.abort();no(e);}});}
function entries(keys,values,type){return new Map(keys.flatMap((key,index)=>{if(!Number.isInteger(key)||key<0||key>4)return [];const raw=values[index],valid=raw&&raw.version===1&&raw.state?.slot===key&&Number.isFinite(raw.savedAt);return [[key,valid?{...raw,type}:{...raw,type,invalid:true}]];}));}
const slots=()=>tx(['slots','autosaves'],'readonly',t=>{const manual=t.objectStore('slots'),automatic=t.objectStore('autosaves'),a=manual.getAll(),ak=manual.getAllKeys(),b=automatic.getAll(),bk=automatic.getAllKeys();return ()=>({manual:entries(ak.result,a.result,'manual'),auto:entries(bk.result,b.result,'auto')});});
const active=()=>tx('metadata','readonly',t=>{const r=t.objectStore('metadata').get('active');return ()=>r.result;});
async function save(state,type='manual',confirmed=false){if(!Number.isInteger(state.slot)||state.slot<0||state.slot>4)throw Error('저장 슬롯을 확인해 주세요');const name=type==='auto'?'autosaves':'slots',entry={version:1,type,savedAt:Date.now(),state:structuredClone(state)};return tx([name,'metadata'],'readwrite',t=>{const store=t.objectStore(name);store.put(entry,state.slot);t.objectStore('metadata').put({slot:state.slot,type},'active');t.objectStore('metadata').delete('suspended-play');});}
async function newGame(state,confirmed=false){if(!Number.isInteger(state.slot)||state.slot<0||state.slot>4)throw Error('저장 슬롯을 확인해 주세요');return tx(['slots','autosaves','metadata'],'readwrite',t=>{const req=t.objectStore('slots').get(state.slot),auto=t.objectStore('autosaves').get(state.slot);let conflict;const commit=()=>{if(req.readyState!=='done'||auto.readyState!=='done')return;if((req.result||auto.result)&&!confirmed){conflict=Error('기존 기록을 덮어쓰려면 확인이 필요해요');t.abort();return;}t.objectStore('slots').put({version:1,type:'manual',savedAt:Date.now(),state:structuredClone(state)},state.slot);t.objectStore('autosaves').delete(state.slot);t.objectStore('metadata').put({slot:state.slot,type:'manual'},'active');t.objectStore('metadata').delete('suspended-play');};req.onsuccess=auto.onsuccess=commit;return ()=>state;});}
const setActive=(slot,type)=>tx('metadata','readwrite',t=>t.objectStore('metadata').put({slot,type},'active'));
const suspend=async(state,pending=Promise.resolve())=>{const copy=structuredClone(state);await pending.catch(()=>{});return tx('metadata','readwrite',t=>t.objectStore('metadata').put(copy,'suspended-play'));};const resume=()=>tx('metadata','readonly',t=>{const r=t.objectStore('metadata').get('suspended-play');return ()=>r.result;});
const api={suspend,resume,DB,open,slots,active,save,newGame,setActive,close:()=>{connection?.close();connection=null;}};window.PixelyGameStore=api;addEventListener('pagehide',api.close);
})();
