'use strict';
(()=>{const D=typeof module!=='undefined'&&module.exports?require('./game-data.js'):window.PixelyGameData;
const id=v=>typeof v==='string'&&/^[a-z0-9][a-z0-9_-]{0,79}$/i.test(v)&&!['constructor','prototype','__proto__'].includes(v);
const clamp=(n,a,b,d=a)=>Number.isFinite(Number(n))?Math.min(b,Math.max(a,Number(n))):d;
const plain=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
function content(value){
 const v=structuredClone(value||D.defaults());if(JSON.stringify(v).length>1000000)throw Error('게임 데이터는 1MB 이하로 구성해 주세요');
 for(const kind of ['locations','characters','items','puzzles']){if(!Array.isArray(v[kind])||v[kind].length>500)throw Error(kind+' 목록을 확인해 주세요');const seen=new Set();for(const r of v[kind]){if(!r||!id(r.id)||seen.has(r.id))throw Error('고유 ID를 확인해 주세요');seen.add(r.id);if(typeof r.name==='string'&&r.name.length>100)throw Error('이름이 너무 길어요');}}
 if(!v.events||typeof v.events!=='object'||Array.isArray(v.events))throw Error('이벤트 목록이 필요해요');
 const has=(kind,key)=>id(key)&&v[kind].some(r=>r.id===key),event=key=>{if(key&&(!id(key)||!Object.hasOwn(v.events,key)))throw Error('연결된 이벤트를 찾지 못했어요: '+key);};
 function checks(list){if(list===undefined)return;if(!Array.isArray(list)||list.length>100)throw Error('조건은 목록으로 적어 주세요');for(const c of list)if(!c||!['flag','item','not-item','puzzle','visit'].includes(c.type)||!id(c.id))throw Error('조건 종류와 ID를 확인해 주세요');}
 function rows(list,label){if(!Array.isArray(list)||list.length>200)throw Error(label+' 목록을 확인해 주세요');const seen=new Set();for(const row of list){if(!row||!id(row.id)||seen.has(row.id))throw Error(label+' ID를 확인해 주세요');seen.add(row.id);checks(row.condition);}return list;}
 for(const location of v.locations){rows(location.actors||[],'등장인물');for(const actor of location.actors||[])if(!has('characters',actor.id))throw Error('등록된 캐릭터를 배치해 주세요');rows(location.exits||[],'이동 지점');for(const exit of location.exits||[])if(!has('locations',exit.to))throw Error('이동할 장소를 먼저 등록해 주세요');event(location.enter);rows(location.objects||[],'오브젝트');for(const object of location.objects||[]){if(!['inspect','talk','use','move'].includes(object.kind))throw Error('오브젝트 동작을 확인해 주세요');if(!object.rect||['x','y','w','h'].some(k=>!Number.isFinite(Number(object.rect[k]))))throw Error('클릭 영역 좌표를 확인해 주세요');if(object.kind==='move'&&!has('locations',object.to))throw Error('오브젝트의 이동 장소를 확인해 주세요');event(object.event);if(object.repeat!==undefined&&!Array.isArray(object.repeat))throw Error('반복 조사는 이벤트 목록으로 적어 주세요');for(const key of object.repeat||[])event(key);if(object.variants!==undefined&&(!Array.isArray(object.variants)||object.variants.length>200))throw Error('조건별 조사는 목록으로 적어 주세요');for(const variant of object.variants||[]){if(!variant)throw Error('조건별 조사를 확인해 주세요');checks(variant.condition);event(variant.event);}if(object.use!==undefined&&(!object.use||typeof object.use!=='object'||Array.isArray(object.use)))throw Error('아이템 사용 연결을 확인해 주세요');for(const [item,use]of Object.entries(object.use||{})){if(!has('items',item)||!use)throw Error('사용 아이템 ID를 확인해 주세요');event(use.event);}}}
 if(!has('locations',v.start))throw Error('시작 장소가 없어요');event(v.opening);for(const character of v.characters)event(character.talk);for(const puzzle of v.puzzles)event(puzzle.success);
 const validSteps=new Set(['say','choice','flag','give','take','collect','move','actor','image','sfx','shake','dim','wait','goal','puzzle','complete','chapter','object','world']);
 function check(steps,depth=0){if(!Array.isArray(steps)||steps.length>300||depth>8)throw Error('이벤트 단계가 너무 많아요');for(const step of steps){if(!step||typeof step!=='object')throw Error('이벤트 단계를 확인해 주세요');checks(step.condition);if(step.id!==undefined&&!id(step.id))throw Error('이벤트 대상 ID를 확인해 주세요');if(step.location!==undefined&&!has('locations',step.location))throw Error('이벤트 장소를 확인해 주세요');if(!validSteps.has(step.type))throw Error('지원하지 않는 이벤트 단계: '+step.type);if(step.type==='say'){if(typeof step.text!=='string'||step.text.length>1000)throw Error('대사를 1000자 이하로 적어 주세요');if(step.actor!==undefined&&!has('characters',step.actor))throw Error('대사의 캐릭터 ID를 확인해 주세요');}if(['give','take'].includes(step.type)&&(!has('items',step.id)||(step.count!==undefined&&(!Number.isInteger(step.count)||step.count<1||step.count>999))))throw Error('아이템과 수량을 확인해 주세요');if(step.type==='puzzle'&&!has('puzzles',step.id))throw Error('퍼즐 ID를 확인해 주세요');if(step.type==='actor'&&!has('characters',step.id))throw Error('캐릭터 ID를 확인해 주세요');if(['move','world'].includes(step.type)&&!has('locations',step.to))throw Error('이동할 장소를 확인해 주세요');if(step.type==='choice'){if(!Array.isArray(step.options)||step.options.length<2||step.options.length>4)throw Error('선택지는 2~4개로 구성해 주세요');for(const option of step.options){if(!option)throw Error('선택지 문구를 확인해 주세요');checks(option.condition);if(typeof option.text!=='string'||option.text.length>100)throw Error('선택지 문구를 확인해 주세요');check(option.steps||[],depth+1);}}}}
 for(const [key,steps]of Object.entries(v.events)){if(!id(key))throw Error('이벤트 ID를 확인해 주세요');check(steps);}return v;
}
function conditions(list,s){return (list||[]).every(c=>c.type==='flag'?s.flags[c.id]===(c.value??true):c.type==='item'?(s.inventory[c.id]||0)>=(c.count||1):c.type==='not-item'?!(s.inventory[c.id]>0):c.type==='puzzle'?s.puzzles[c.id]===true:c.type==='visit'?(s.visits[c.id]||0)>=(c.count||1):false);}
function create(data,slot,outfit=null){return {version:1,slot,chapter:'prologue',location:data.start,flags:{},visits:{[data.start]:1},investigations:{},inventory:{},choices:{},puzzles:{},collections:{},chapters:{prologue:{unlocked:true,cleared:false}},actors:{},run:null,log:[],readLines:{},goal:'',completedGoals:[],outfit,playMs:0,selectedItem:null,updatedAt:Date.now()};}
function restore(raw,data){if(raw?.version!==1||!Number.isInteger(raw.slot)||raw.slot<0||raw.slot>4||!data.locations.some(l=>l.id===raw.location))throw Error('호환되는 저장 기록을 찾지 못했어요');const s=structuredClone(raw);for(const k of ['flags','visits','investigations','inventory','choices','puzzles','collections','chapters','actors','readLines'])s[k]=plain(s[k]);s.log=Array.isArray(s.log)?s.log.filter(line=>line&&typeof line.speaker==='string'&&typeof line.text==='string').slice(-300):[];s.playMs=clamp(s.playMs,0,1e12,0);s.completedGoals=Array.isArray(s.completedGoals)?s.completedGoals.filter(v=>typeof v==='string').slice(-300):[];s.goal=typeof s.goal==='string'?s.goal:'';if(s.run&&(!Array.isArray(s.run.steps)||!Number.isInteger(s.run.index)||s.run.index<0||s.run.index>s.run.steps.length))throw Error('이벤트 저장 기록이 올바르지 않아요');if(s.run){content({...data,events:{...data.events,'saved-event':s.run.steps}});const step=current(s),p=s.run.presentation;if(p&&step?.type==='say'){p.count=clamp(p.count,0,step.text.length,0);p.elapsed=clamp(p.elapsed,0,30000,0);}else if(p?.remaining!==undefined)p.remaining=clamp(p.remaining,0,30000,0);}return s;}
function start(s,data,event){if(s.run)return false;const steps=data.events[event];if(!steps)return false;s.run={id:event,index:0,steps:structuredClone(steps)};return true;}
const current=s=>s.run?.steps[s.run.index];
function next(s){if(s.run){s.run.index++;if(s.run.index>=s.run.steps.length)s.run=null;}}
function choose(s,index){const step=current(s);if(step?.type!=='choice'||!step.options[index]||!conditions(step.options[index].condition,s))return false;s.choices[step.id||s.run.id]=index;s.run.steps.splice(s.run.index,1,...structuredClone(step.options[index].steps||[]));if(s.run.index>=s.run.steps.length)s.run=null;return true;}
function apply(s,data,step){switch(step.type){case 'flag':if(id(step.id))s.flags[step.id]=step.value??true;break;case 'give':if(data.items.some(i=>i.id===step.id))s.inventory[step.id]=(s.inventory[step.id]||0)+(step.count||1);break;case 'take':s.inventory[step.id]=Math.max(0,(s.inventory[step.id]||0)-(step.count||1));break;case 'collect':if(id(step.id))s.collections[step.id]=true;break;case 'complete':if(id(step.id))s.puzzles[step.id]=true;break;case 'goal':if(s.goal)s.completedGoals.push(s.goal);s.goal=String(step.text||'').slice(0,300);break;case 'actor':{const location=step.location||s.location;s.actors[location]||={};s.actors[location][step.id]={...(s.actors[location][step.id]||{}),...plain(step.state)};break;}case 'chapter':s.chapter=step.id;s.chapters[step.id]={unlocked:true,cleared:step.cleared===true};break;case 'object':{s.objects||={};s.objects[step.location||s.location]||={};s.objects[step.location||s.location][step.id]={visible:step.visible!==false};break;}case 'world':case 'move':return move(s,data,step.to,true);default:break;}return true;}
function move(s,data,to,force=false){if(!data.locations.some(l=>l.id===to))return false;const from=data.locations.find(l=>l.id===s.location),edge=from?.exits?.some(e=>e.to===to&&conditions(e.condition,s)),object=from?.objects?.some(o=>o.kind==='move'&&o.to===to&&s.objects?.[from.id]?.[o.id]?.visible!==false&&conditions(o.condition,s));if(!force&&!edge&&!object)return false;s.location=to;s.visits[to]=(s.visits[to]||0)+1;s.chapter=data.locations.find(l=>l.id===to).chapter||s.chapter;return true;}
function investigate(s,data,object,item=null){if(s.run||!conditions(object.condition,s))return false;let event=object.event;if(item){if(!(s.inventory[item]>0))return false;const use=object.use?.[item];event=use?.event||'wrong-item';if(!data.events[event])return false;if(use?.consume)s.inventory[item]--;s.selectedItem=null;}else{const count=s.investigations[object.id]||0;const variant=(object.variants||[]).find(v=>conditions(v.condition,s));event=variant?.event||(count>0&&object.repeat?.length?object.repeat[Math.min(count-1,object.repeat.length-1)]:event);if(!data.events[event])return false;s.investigations[object.id]=count+1;}return start(s,data,event);}
function actors(s,location){return (location.actors||[]).map(a=>({...a,...(s.actors[location.id]?.[a.id]||{})})).filter(a=>a.visible!==false&&conditions(a.condition,s));}
function rect(v){return {x:clamp(v?.x,0,100,0),y:clamp(v?.y,0,100,0),w:clamp(v?.w,1,100,10),h:clamp(v?.h,1,100,10)};}
function cancelPuzzle(s){if(current(s)?.type!=='puzzle')return false;s.run=null;return true;}
function imageTransform(v){return {x:clamp(v?.x,-100,100,0),y:clamp(v?.y,-100,100,0),scale:clamp(v?.scale,20,300,100),rotate:clamp(v?.rotate,-180,180,0)};}
const api={cancelPuzzle,imageTransform,id,clamp,content,conditions,create,restore,start,current,next,choose,apply,move,investigate,actors,rect};if(typeof module!=='undefined'&&module.exports)module.exports=api;else window.PixelyGameModel=api;
})();
