'use strict';
(()=>{const DB='pixely-adventure-game';let connection;function open(){if(connection)return Promise.resolve(connection);return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{r.result.createObjectStore('slots');r.result.createObjectStore('autosaves');r.result.createObjectStore('metadata');};r.onerror=()=>no(r.error);r.onblocked=()=>no(Error('다른 게임 탭을 닫고 다시 시도해 주세요'));r.onsuccess=()=>{connection=r.result;connection.onversionchange=()=>{connection.close();connection=null;};ok(connection);};});}async function tx(names,mode,work){const db=await open();return new Promise((ok,no)=>{const t=db.transaction(names,mode);let value;t.oncomplete=()=>ok(typeof value==='function'?value():value);t.onabort=()=>no(t.error||Error('저장하지 못했어요'));try{value=work(t);}catch(e){t.abort();no(e);}});}
const slots=()=>tx(['slots','autosaves'],'readonly',t=>{const a=t.objectStore('slots').getAll(),b=t.objectStore('autosaves').getAll();return ()=>({manual:new Map(a.result.map(r=>[r.state.slot,r])),auto:new Map(b.result.map(r=>[r.state.slot,r]))});});
const active=()=>tx('metadata','readonly',t=>{const r=t.objectStore('metadata').get('active');return ()=>r.result;});
async function save(state,type='manual',confirmed=false){if(!Number.isInteger(state.slot)||state.slot<0||state.slot>4)throw Error('저장 슬롯을 확인해 주세요');const name=type==='auto'?'autosaves':'slots',entry={version:1,type,savedAt:Date.now(),state:structuredClone(state)};return tx([name,'metadata'],'readwrite',t=>{const store=t.objectStore(name);store.put(entry,state.slot);t.objectStore('metadata').put({slot:state.slot,type},'active');});}
async function newGame(state,confirmed=false){return tx(['slots','autosaves','metadata'],'readwrite',t=>{const req=t.objectStore('slots').get(state.slot),auto=t.objectStore('autosaves').get(state.slot);let conflict;const commit=()=>{if(req.readyState!=='done'||auto.readyState!=='done')return;if((req.result||auto.result)&&!confirmed){conflict=Error('기존 기록을 덮어쓰려면 확인이 필요해요');t.abort();return;}t.objectStore('slots').put({version:1,type:'manual',savedAt:Date.now(),state:structuredClone(state)},state.slot);t.objectStore('autosaves').delete(state.slot);t.objectStore('metadata').put({slot:state.slot,type:'manual'},'active');};req.onsuccess=auto.onsuccess=commit;return ()=>state;});}
const setActive=(slot,type)=>tx('metadata','readwrite',t=>t.objectStore('metadata').put({slot,type},'active'));
const api={DB,open,slots,active,save,newGame,setActive,close:()=>{connection?.close();connection=null;}};window.PixelyGameStore=api;addEventListener('pagehide',api.close);
})();
