'use strict';
(()=>{const A=PixelyAdmin,G=PixelyGame,M=PixelyGameModel,R=PixelyGameStore,n=G.node;let previewURLs=[],draft,base='initial',dirty=false,images=new Map(),past=[],future=[],activeKind='locations',activeId='',selectedObject='',selectedActor='',dragEnabled=false;const launch=n('button','장면 편집','game-editor-launch');launch.hidden=true;document.getElementById('game-shell').append(launch);const dialog=n('dialog',undefined,'game-panel game-editor-panel');dialog.innerHTML='<header><h2>플레이 데이터 편집</h2><button data-close aria-label="닫기">×</button></header><p class="game-editor-notice">공통 콘텐츠 편집 · 테스트 플레이는 플레이어 기록에 저장되지 않아요</p><div class="game-editor-tools"></div><p role="status" class="game-editor-status"></p><div class="game-editor-form"></div>';document.body.append(dialog);const root=dialog.querySelector('.game-editor-form'),tools=dialog.querySelector('.game-editor-tools'),status=dialog.querySelector('[role=status]');const names={locations:'장소',characters:'캐릭터',items:'아이템',puzzles:'퍼즐',events:'대화·이벤트'};
const snapshot=()=>({draft:structuredClone(draft),images:structuredClone([...images]),dirty}),checkpoint=()=>{past.push(snapshot());past=past.slice(-40);future=[];},restore=s=>{draft=s.draft;images=new Map(s.images);dirty=s.dirty;draw();preview();},mark=()=>{dirty=true;status.textContent='미반영 편집 · 임시 저장한 뒤 사이트에 반영해 주세요';void cache();},cache=async()=>{try{const db=await R.open();await new Promise((ok,no)=>{const t=db.transaction('metadata','readwrite');t.objectStore('metadata').put({...snapshot(),base},'author-game');t.oncomplete=ok;t.onabort=()=>no(t.error);});}catch(e){G.notify('브라우저 편집 보관 실패 · '+e.message);}};
async function cached(){const db=await R.open();return new Promise((ok,no)=>{const t=db.transaction('metadata','readonly'),r=t.objectStore('metadata').get('author-game');t.oncomplete=()=>ok(r.result);t.onabort=()=>no(t.error);});}
const entries=()=>activeKind==='events'?Object.entries(draft.game.events).map(([id,steps])=>({id,steps})):draft.game[activeKind],entry=()=>entries().find(r=>r.id===activeId)||entries()[0];
function field(label,value,change,type='text',min,max){const l=n('label',label),input=n('input');input.type=type;if(type==='checkbox')input.checked=value===true;else input.value=value??'';if(min!==undefined)input.min=min;if(max!==undefined)input.max=max;if(type==='number')input.step='1';input.onfocus=checkpoint;input.onchange=()=>{change(type==='checkbox'?input.checked:type==='number'?Number(input.value):input.value);mark();preview();};l.append(input);root.append(l);return input;}
function textArea(label,value,change){const l=n('label',label,'wide'),input=n('textarea');input.value=JSON.stringify(value,null,2);input.spellcheck=false;input.onfocus=checkpoint;input.onchange=()=>{try{change(JSON.parse(input.value));M.content(draft.game);mark();status.textContent='편집 적용됨 · 임시 저장 후 반영해 주세요';preview();}catch(e){status.textContent=e.message;}};l.append(input);root.append(l);return input;}
function select(label,options,value,change){const l=n('label',label),input=n('select');for(const o of options){const opt=n('option',o.name||o.id);opt.value=o.id;opt.selected=o.id===value;input.append(opt);}input.onchange=()=>change(input.value);l.append(input);root.append(l);return input;}
function preview(){try{const oldURLs=previewURLs;previewURLs=[];const copy={...draft,assets:{...draft.assets}};for(const [key,value]of images){if(value.path)copy.assets[key]=value;else if(value.blob){copy.assets[key]={...value,path:'',preview:(()=>{const url=URL.createObjectURL(value.blob);previewURLs.push(url);return url;})()};}}G.setContent(copy);oldURLs.forEach(url=>URL.revokeObjectURL(url));}catch(e){status.textContent=e.message;}}
async function upload(id,file){if(!file)return;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>20*1024*1024)throw Error('PNG·JPG·WEBP·GIF 파일을 20MB 이하로 올려 주세요');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>36000000){bitmap.close();throw Error('이미지가 너무 커요');}bitmap.close();checkpoint();images.set(id,{blob:file,transform:{x:0,y:0,scale:100,rotate:0}});mark();draw();preview();}
function imageControls(label,key,setId){const group=n('div',undefined,'wide'),title=n('h3',label),file=n('input');file.type='file';file.accept='image/png,image/jpeg,image/webp,image/gif';file.setAttribute('aria-label',label+' 업로드');file.onchange=G.safeAction(async()=>{await upload(key,file.files[0]);setId(key);mark();preview();});const remove=n('button','이미지 삭제');remove.type='button';remove.onclick=()=>{checkpoint();images.delete(key);delete draft.assets[key];setId('');mark();preview();draw();};group.append(title,file,remove);const value=images.get(key)||draft.assets[key];if(value){const img=n('img');img.style.cssText='width:120px;height:100px;object-fit:contain;display:block';img.src=value.blob?URL.createObjectURL(value.blob):A.imageURL(value.path);img.onload=()=>{if(value.blob)URL.revokeObjectURL(img.src);};group.append(img);}root.append(group);if(value){for(const [prop,text,min,max]of [['x','이미지 X',-100,100],['y','이미지 Y',-100,100],['scale','이미지 크기',20,300],['rotate','이미지 회전',-180,180]])field(text,value.transform?.[prop]??(prop==='scale'?100:0),v=>{const current=images.get(key)||structuredClone(draft.assets[key]);current.transform={...current.transform,[prop]:M.clamp(v,min,max)};images.set(key,current);},'number',min,max);}}
function draw(){root.replaceChildren();if(!draft)return;select('편집 종류',Object.keys(names).map(id=>({id,name:names[id]})),activeKind,v=>{activeKind=v;activeId='';draw();});const records=entries();if(!records.length){const blank=n('p','아직 등록된 항목이 없어요');root.append(blank);}else{const rec=entry();activeId=rec.id;select('항목',records.map(r=>({id:r.id,name:r.name||r.title||r.id})),rec.id,v=>{activeId=v;selectedObject=selectedActor='';draw();});if(activeKind==='events'){textArea('이벤트 단계 · say / choice / give / take / collect / actor / object / move / world / puzzle / image / sfx / wait / dim / shake / goal / chapter',rec.steps,v=>draft.game.events[rec.id]=v);const test=n('button','이 이벤트 테스트');test.onclick=()=>{dialog.close();if(!G.getState())G.testStart();G.testScene(G.getState()?.location||draft.game.start);G.startEvent(rec.id);};root.append(test);}else{field('이름',rec.name||rec.title||'',v=>{if(activeKind==='puzzles')rec.title=v;else rec.name=v;});
if(activeKind==='locations'){imageControls('장소 배경','scene:'+rec.id+':background',id=>rec.background=id);select('기존 배경', [{id:'house',name:'기존 집 앞'},{id:'blank',name:'빈 공간'}],rec.builtin||'blank',v=>{checkpoint();rec.builtin=v;mark();preview();});textArea('이동 지점 · to / side / condition',rec.exits||[],v=>rec.exits=v);textArea('장소 오브젝트 · id / name / kind / rect / event / repeat / variants / use / condition',rec.objects||[],v=>rec.objects=v);
if(rec.objects?.length){const object=rec.objects.find(o=>o.id===selectedObject)||rec.objects[0];selectedObject=object.id;select('클릭 영역 대상',rec.objects,object.id,v=>{selectedObject=v;draw();});for(const [prop,label]of [['x','영역 X'],['y','영역 Y'],['w','영역 너비'],['h','영역 높이']])field(label,object.rect?.[prop]||0,v=>{object.rect=M.rect({...object.rect,[prop]:v});},'number',0,100);}
textArea('장소별 캐릭터 · id / emotion / visible / x / y / scale / flip / rotate / z / condition',rec.actors||[],v=>rec.actors=v);if(rec.actors?.length){const actor=rec.actors.find(a=>a.id===selectedActor)||rec.actors[0];selectedActor=actor.id;select('배치할 캐릭터',rec.actors.map(a=>({id:a.id,name:draft.game.characters.find(c=>c.id===a.id)?.name||a.id})),actor.id,v=>{selectedActor=v;draw();});for(const [prop,label,min,max]of [['x','캐릭터 X',0,100],['y','캐릭터 Y',0,100],['scale','캐릭터 크기',10,300],['rotate','캐릭터 회전',-180,180],['z','캐릭터 표시 순서',0,50]])field(label,actor[prop]??(prop==='scale'?100:0),v=>actor[prop]=M.clamp(v,min,max),'number',min,max);field('캐릭터 표시',actor.visible!==false,v=>actor.visible=v,'checkbox');field('좌우 반전',actor.flip,v=>actor.flip=v,'checkbox');field('표정 ID',actor.emotion||'normal',v=>actor.emotion=v);textArea('캐릭터 등장 조건',actor.condition||[],v=>actor.condition=v);}
const test=n('button','이 장면 테스트');test.onclick=()=>{if(!G.getState())G.testStart();G.testScene(rec.id);dialog.close();};root.append(test);
}else if(activeKind==='characters'){field('대화 이벤트 ID',rec.talk||'',v=>rec.talk=v);rec.images||={};let emotion='normal';const emotionInput=field('편집할 표정 ID',emotion,v=>{emotion=M.id(v)?v:'normal';drawEmotion();});const holder=n('div',undefined,'wide');root.append(holder);function drawEmotion(){const oldRootChildren=[...root.children];imageControls('표정 이미지 · '+emotion,'character:'+rec.id+':'+emotion,id=>{if(id)rec.images[emotion]=id;else delete rec.images[emotion];});for(const c of [...root.children].filter(c=>!oldRootChildren.includes(c)))holder.append(c);}drawEmotion();emotionInput.onchange=()=>{emotion=M.id(emotionInput.value)?emotionInput.value:'normal';holder.replaceChildren();drawEmotion();};textArea('표정 이미지 ID 목록',rec.images,v=>rec.images=v);
}else if(activeKind==='items'){field('설명',rec.description||'',v=>rec.description=v);field('콜렉션 기록 ID',rec.collection||'',v=>rec.collection=v);imageControls('아이템 이미지','item:'+rec.id,id=>rec.image=id);}else if(activeKind==='puzzles'){field('문제',rec.question||'',v=>rec.question=v);field('정답',rec.answer||'',v=>rec.answer=v);field('성공 이벤트 ID',rec.success||'',v=>rec.success=v);}}
}
const create=n('button',names[activeKind]+' 추가');create.onclick=()=>{const id=prompt('새 항목 ID · 영문/숫자/하이픈');if(!id)return;if(!M.id(id)||records.some(r=>r.id===id)){status.textContent='중복되지 않는 영문 ID를 입력해 주세요';return;}checkpoint();if(activeKind==='events')draft.game.events[id]=[];else draft.game[activeKind].push(activeKind==='locations'?{id,name:'새 장소',builtin:'blank',actors:[],objects:[],exits:[]}:activeKind==='characters'?{id,name:'새 캐릭터',images:{}}:activeKind==='puzzles'?{id,title:'새 퍼즐',question:'',answer:'',success:''}:{id,name:'새 아이템',description:'',image:''});activeId=id;mark();draw();};root.append(create);textArea('시작 장소·첫 이벤트·자동 저장 시점', {start:draft.game.start,opening:draft.game.opening,autosave:draft.game.autosave},v=>{draft.game.start=v.start;draft.game.opening=v.opening;draft.game.autosave=v.autosave;});}
function button(label,fn){const b=n('button',label);b.type='button';b.onclick=G.safeAction(fn);tools.append(b);return b;}
button('되돌리기',()=>{if(!past.length)return;future.push(snapshot());restore(past.pop());void cache();});button('다시 실행',()=>{if(!future.length)return;past.push(snapshot());restore(future.pop());void cache();});button('임시 저장',async()=>{M.content(draft.game);status.textContent='서버에 임시 저장 중…';const prepared=await A.prepare(draft,images),result=await A.save(prepared,base);draft=result;base=result.revision;images=new Map(Object.entries(result.assets));dirty=false;await cache();status.textContent='임시 저장됨 · 일반 화면에는 아직 반영되지 않았어요';preview();draw();});button('미리보기',()=>{preview();dialog.close();});button('사이트에 반영',async()=>{if(dirty)throw Error('먼저 임시 저장해 주세요');await A.publish(base);status.textContent='사이트에 반영됐어요';});button('클릭 영역 표시·드래그',()=>{dragEnabled=!dragEnabled;document.getElementById('play-screen').classList.toggle('hitboxes',dragEnabled);dialog.close();G.notify(dragEnabled?'선택한 이미지·영역을 드래그해서 위치 조절':'드래그 편집 해제');});button('테스트 시작',()=>{G.testStart();dialog.close();});button('모드 끄기',()=>{dialog.close();dragEnabled=false;document.getElementById('play-screen').classList.remove('hitboxes');A.setMode(false);location.reload();});
async function open(){if(!A.isEditor())return;if(!draft){const server=await A.request('draft'),local=await cached();if(local?.dirty&&local.base===server.revision){draft=local.draft;images=new Map(local.images);base=local.base;dirty=true;}else {draft=server;images=new Map(Object.entries(server.assets));base=server.revision;}}preview();status.textContent=dirty?'임시 편집 있음':base==='initial'?'아직 서버에 저장한 편집이 없어요':'서버 임시 저장본';draw();dialog.showModal();}
launch.onclick=G.safeAction(open);dialog.querySelector('[data-close]').onclick=()=>dialog.close();function mode(){launch.hidden=!A.isEditor();if(!A.isEditor()&&dialog.open)dialog.close();}A.ready.then(mode);addEventListener('pixely:developer-mode',mode);
let drag;document.getElementById('play-screen').addEventListener('pointerdown',e=>{if(!dragEnabled||!A.isEditor()||!draft)return;const el=e.target.closest('[data-object],[data-actor]');if(!el)return;const location=draft.game.locations.find(l=>l.id===G.getState()?.location);const record=el.dataset.object?location?.objects.find(o=>o.id===el.dataset.object):location?.actors.find(a=>a.id===el.dataset.actor);if(!record)return;checkpoint();G.pause(true);drag={record,el,x:e.clientX,y:e.clientY,startX:record.rect?.x??record.x,startY:record.rect?.y??record.y,rect:!!record.rect};el.setPointerCapture(e.pointerId);e.preventDefault();e.stopImmediatePropagation();},true);
document.getElementById('play-screen').addEventListener('pointermove',e=>{if(!drag)return;const box=document.getElementById('play-screen').getBoundingClientRect(),x=M.clamp(drag.startX+(e.clientX-drag.x)/box.width*100,0,100),y=M.clamp(drag.startY+(e.clientY-drag.y)/box.height*100,0,100);if(drag.rect){drag.record.rect.x=x;drag.record.rect.y=y;drag.el.style.left=x+'%';drag.el.style.top=y+'%';}else{drag.record.x=x;drag.record.y=y;drag.el.style.left=x-11+'%';drag.el.style.bottom=100-y+'%';}});
document.getElementById('play-screen').addEventListener('pointerup',e=>{if(!drag)return;drag.el.releasePointerCapture(e.pointerId);drag=null;mark();preview();G.pause(false);e.preventDefault();},true);document.getElementById('play-screen').addEventListener('click',e=>{if(dragEnabled){e.preventDefault();e.stopImmediatePropagation();}},true);
})();
