'use strict';
(()=>{const D=typeof module!=='undefined'&&module.exports?require('./game-data.js'):window.PixelyGameData;
const id=v=>typeof v==='string'&&/^[a-z0-9][a-z0-9_-]{0,79}$/i.test(v)&&!['constructor','prototype','__proto__'].includes(v);
const clamp=(n,a,b,d=a)=>Number.isFinite(Number(n))?Math.min(b,Math.max(a,Number(n))):d;
const plain=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
function content(value){const v=structuredClone(value||D.defaults());if(JSON.stringify(v).length>1000000)throw Error('게임 데이터는 1MB 이하로 구성해 주세요');for(const kind of ['locations','characters','items','puzzles']){if(!Array.isArray(v[kind])||v[kind].length>500)throw Error(kind+' 목록을 확인해 주세요');const seen=new Set();for(const r of v[kind]){if(!id(r.id)||seen.has(r.id))throw Error('고유 ID를 확인해 주세요');seen.add(r.id);if(typeof r.name==='string'&&r.name.length>100)throw Error('이름이 너무 길어요');}}if(!v.locations.some(l=>l.id===v.start))throw Error('시작 장소가 없어요');if(!v.events||Array.isArray(v.events))throw Error('이벤트 목록이 필요해요');const validSteps=new Set(['say','choice','flag','give','take','collect','move','actor','image','sfx','shake','dim','wait','goal','puzzle','complete','chapter','object','world']);function check(steps,depth=0){if(!Array.isArray(steps)||steps.length>300||depth>8)throw Error('이벤트 단계가 너무 많아요');for(const s of steps){if(s.id!==undefined&&!id(s.id))throw Error('이벤트 대상 ID를 확인해 주세요');if(s.location!==undefined&&!id(s.location))throw Error('이벤트 장소 ID를 확인해 주세요');if(!validSteps.has(s.type))throw Error('지원하지 않는 이벤트 단계: '+s.type);if(s.type==='say'&&(typeof s.text!=='string'||s.text.length>1000))throw Error('대사를 1000자 이하로 적어 주세요');if(s.type==='choice'){if(!Array.isArray(s.options)||s.options.length<2||s.options.length>4)throw Error('선택지는 2~4개로 구성해 주세요');s.options.forEach(o=>check(o.steps||[],depth+1));}}}for(const [k,steps]of Object.entries(v.events)){if(!id(k))throw Error('이벤트 ID를 확인해 주세요');check(steps);}return v;}
function conditions(list,s){return (list||[]).every(c=>c.type==='flag'?s.flags[c.id]===(c.value??true):c.type==='item'?(s.inventory[c.id]||0)>=(c.count||1):c.type==='not-item'?!(s.inventory[c.id]>0):c.type==='puzzle'?s.puzzles[c.id]===true:c.type==='visit'?(s.visits[c.id]||0)>=(c.count||1):false);}
function create(data,slot,outfit=null){return {version:1,slot,chapter:'prologue',location:data.start,flags:{},visits:{[data.start]:1},investigations:{},inventory:{},choices:{},puzzles:{},collections:{},chapters:{prologue:{unlocked:true,cleared:false}},actors:{},run:null,log:[],readLines:{},goal:'',completedGoals:[],outfit,playMs:0,selectedItem:null,updatedAt:Date.now()};}
function restore(raw,data){if(raw?.version!==1||!Number.isInteger(raw.slot)||raw.slot<0||raw.slot>4||!data.locations.some(l=>l.id===raw.location))throw Error('호환되는 저장 기록을 찾지 못했어요');const s=structuredClone(raw);for(const k of ['flags','visits','investigations','inventory','choices','puzzles','collections','chapters','actors','readLines'])s[k]=plain(s[k]);s.log=Array.isArray(s.log)?s.log.slice(-300):[];s.playMs=clamp(s.playMs,0,1e12,0);s.completedGoals=s.completedGoals||[];if(s.run&&(!Array.isArray(s.run.steps)||!Number.isInteger(s.run.index)||s.run.index<0||s.run.index>s.run.steps.length))throw Error('이벤트 저장 기록이 올바르지 않아요');return s;}
function start(s,data,event){if(s.run)return false;const steps=data.events[event];if(!steps)return false;s.run={id:event,index:0,steps:structuredClone(steps)};return true;}
const current=s=>s.run?.steps[s.run.index];
function next(s){if(s.run){s.run.index++;if(s.run.index>=s.run.steps.length)s.run=null;}}
function choose(s,index){const step=current(s);if(step?.type!=='choice'||!step.options[index])return false;s.choices[step.id||s.run.id]=index;s.run.steps.splice(s.run.index,1,...structuredClone(step.options[index].steps||[]));if(s.run.index>=s.run.steps.length)s.run=null;return true;}
function apply(s,data,step){switch(step.type){case 'flag':if(id(step.id))s.flags[step.id]=step.value??true;break;case 'give':if(data.items.some(i=>i.id===step.id))s.inventory[step.id]=(s.inventory[step.id]||0)+(step.count||1);break;case 'take':s.inventory[step.id]=Math.max(0,(s.inventory[step.id]||0)-(step.count||1));break;case 'collect':if(id(step.id))s.collections[step.id]=true;break;case 'complete':if(id(step.id))s.puzzles[step.id]=true;break;case 'goal':if(s.goal)s.completedGoals.push(s.goal);s.goal=String(step.text||'').slice(0,300);break;case 'actor':{const location=step.location||s.location;s.actors[location]||={};s.actors[location][step.id]={...(s.actors[location][step.id]||{}),...plain(step.state)};break;}case 'chapter':s.chapter=step.id;s.chapters[step.id]={unlocked:true,cleared:step.cleared===true};break;case 'object':{s.objects||={};s.objects[step.location||s.location]||={};s.objects[step.location||s.location][step.id]={visible:step.visible!==false};break;}case 'world':case 'move':return move(s,data,step.to,true);default:break;}return true;}
function move(s,data,to,force=false){if(!data.locations.some(l=>l.id===to))return false;if(!force&&!data.locations.find(l=>l.id===s.location)?.exits?.some(e=>e.to===to&&conditions(e.condition,s)))return false;s.location=to;s.visits[to]=(s.visits[to]||0)+1;s.chapter=data.locations.find(l=>l.id===to).chapter||s.chapter;return true;}
function investigate(s,data,object,item=null){if(s.run||!conditions(object.condition,s))return false;let event=object.event;if(item){if(!(s.inventory[item]>0))return false;const use=object.use?.[item];event=use?.event||'wrong-item';if(!data.events[event])return false;if(use?.consume)s.inventory[item]--;s.selectedItem=null;}else{const count=s.investigations[object.id]||0;const variant=(object.variants||[]).find(v=>conditions(v.condition,s));event=variant?.event||(count>0&&object.repeat?.length?object.repeat[Math.min(count-1,object.repeat.length-1)]:event);s.investigations[object.id]=count+1;}return start(s,data,event);}
function actors(s,location){return (location.actors||[]).map(a=>({...a,...(s.actors[location.id]?.[a.id]||{})})).filter(a=>a.visible!==false&&conditions(a.condition,s));}
function rect(v){return {x:clamp(v?.x,0,100,0),y:clamp(v?.y,0,100,0),w:clamp(v?.w,1,100,10),h:clamp(v?.h,1,100,10)};}
const api={id,clamp,content,conditions,create,restore,start,current,next,choose,apply,move,investigate,actors,rect};if(typeof module!=='undefined'&&module.exports)module.exports=api;else window.PixelyGameModel=api;
})();
