'use strict';
(() => {
  const A = PixelyAdmin, G = PixelyGame, M = PixelyGameModel, R = PixelyGameStore, T=PixelyDialogue, n = G.node;
  const names = {monologue:'프롤로그 독백', locations:'장소', characters:'캐릭터', items:'아이템', puzzles:'퍼즐', events:'대화·이벤트'};
  let draft, base='initial', dirty=false, busy=false, images=new Map(), past=[], future=[], previewURLs=[];
  const editingEmotions=new Map(),focusedLines=new Map();let previewLocation='',editorView='text';
  let activeKind=['monologue','events','characters'].includes(new URLSearchParams(location.search).get('editor'))?new URLSearchParams(location.search).get('editor'):'locations', activeId='', selectedObject='', selectedActor='', selectedLayer='', dragEnabled=false, cacheChain=Promise.resolve();
  const launch=n('button','플레이 편집','game-editor-launch'); launch.hidden=true;
  document.getElementById('game-shell').append(launch);
  const dialog=n('dialog',undefined,'game-panel game-editor-panel');
  dialog.setAttribute('aria-labelledby','game-editor-title');
  dialog.innerHTML='<header><div><p class="editor-eyebrow">개발자 모드</p><h2 id="game-editor-title">플레이 편집</h2></div><button data-close aria-label="편집 창 닫기">×</button></header><nav class="game-editor-tabs" aria-label="편집 종류"></nav><div class="game-editor-form"></div><footer class="game-editor-footer"><p role="status" aria-live="polite" class="game-editor-status"></p><div class="game-editor-tools"></div></footer>';
  document.body.append(dialog);
  let root=dialog.querySelector('.game-editor-form');
  const formRoot=root, tools=dialog.querySelector('.game-editor-tools'), tabs=dialog.querySelector('.game-editor-tabs'), status=dialog.querySelector('[role=status]');
  const snapshot=()=>({draft:structuredClone(draft),images:structuredClone([...images]),dirty});
  function controls(){if(typeof dragButton!=='undefined')dragButton.hidden=activeKind==='monologue';undoButton.disabled=!past.length||busy;redoButton.disabled=!future.length||busy;tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===activeKind)));}
  function checkpoint(){past.push(snapshot());past=past.slice(-40);future=[];controls();}
  function restore(s){draft=s.draft;images=new Map(s.images);dirty=s.dirty;draw();preview();showStatus();}
  function showStatus(text){status.textContent=text||(dirty?'저장 전 · 이 브라우저에 편집 내용 보관 중':'저장됨 · 사이트 반영은 별도');status.dataset.error='false';}
  function mark(){dirty=true;showStatus();void cache();}
  function cache(){const value={...snapshot(),base};cacheChain=cacheChain.catch(()=>{}).then(async()=>{const db=await R.open();await new Promise((ok,no)=>{const t=db.transaction('metadata','readwrite');t.objectStore('metadata').put(value,'author-game');t.oncomplete=ok;t.onabort=()=>no(t.error);});});cacheChain.catch(e=>G.notify('브라우저 편집 보관 실패 · '+e.message));return cacheChain;}
  async function cached(){const db=await R.open();return new Promise((ok,no)=>{const t=db.transaction('metadata','readonly'),r=t.objectStore('metadata').get('author-game');t.oncomplete=()=>ok(r.result);t.onabort=()=>no(t.error);});}
  function entries(){return activeKind==='monologue'?draft.game.monologue.pages:activeKind==='events'?Object.entries(draft.game.events).map(([id,steps])=>({id,steps})):draft.game[activeKind];}
  function eventName(id){const game=draft.game;if(game.eventNames?.[id])return game.eventNames[id];if(id===game.opening)return '처음 시작하는 대화';for(const l of game.locations){if(l.enter===id)return l.name+' · 입장';for(const o of l.objects||[]){if(o.event===id)return o.name+' · 조사';if(o.repeat?.includes(id))return o.name+' · 다시 조사';}}for(const c of game.characters)if(c.talk===id)return c.name+' · 대화';for(const p of game.puzzles)if(p.success===id)return p.title+' · 성공';return id;}
  const recordName=r=>activeKind==='events'?eventName(r.id):r.name||r.title||r.id;
  const eventOptions=()=>Object.keys(draft.game.events).map(id=>({id,name:eventName(id)}));
  const collectionOptions=()=>Object.entries(draft.catalogue.collections).flatMap(([kind,rows])=>rows.map(r=>({id:r.id,name:({people:'인물',cards:'카드',items:'아이템',memories:'추억'})[kind]+' · '+(r.title||r.id)})));
  function within(parent,fn){const old=root;root=parent;try{fn();}finally{root=old;}}
  function section(title,fn,collapsed=false){const wrapper=n(collapsed?'details':'section',undefined,'editor-section wide');if(collapsed)wrapper.append(n('summary',title));else wrapper.append(n('h3',title));const body=n('div',undefined,'editor-section-grid');wrapper.append(body);root.append(wrapper);within(body,fn);return wrapper;}
  function button(label,fn,parent=root){const b=n('button',label);b.type='button';b.onclick=()=>run(fn);parent.append(b);return b;}
  async function run(fn){if(busy)return;try{await fn();}catch(e){status.textContent=e.message;status.dataset.error='true';G.notify(e.message);}}
  function field(label,value,change,type='text',min,max){const l=n('label',label),input=n(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.setAttribute('aria-label',label);if(type==='checkbox')input.checked=value===true;else input.value=value??'';if(min!==undefined)input.min=min;if(max!==undefined)input.max=max;if(type==='number')input.step='1';if(type==='textarea'){input.maxLength=8000;l.classList.add('wide');}input.onfocus=checkpoint;input.onchange=()=>{if(busy)return;change(type==='checkbox'?input.checked:type==='number'?M.clamp(input.value,min??-1e6,max??1e6):input.value);mark();preview();};l.append(input);root.append(l);return input;}
  function select(label,options,value,change,empty=false){const l=n('label',label),input=n('select');input.setAttribute('aria-label',label);const list=empty?[{id:'',name:'연결 안 함'},...options]:options;for(const o of list)input.append(new Option(o.name||o.title||o.id,o.id));if(value&&!list.some(o=>o.id===value))input.append(new Option(value+' · 연결 확인 필요',value));input.value=value||'';input.onchange=()=>{if(busy)return;checkpoint();change(input.value);mark();preview();};l.append(input);root.append(l);return input;}
  function slider(label,value,change,min,max){const wrap=n('label',label,'editor-slider'),pair=n('div'),range=n('input'),num=n('input');range.type='range';num.type='number';for(const el of [range,num]){el.min=min;el.max=max;el.step='1';el.value=value;el.setAttribute('aria-label',label+(el===range?' 슬라이더':''));el.onpointerdown=checkpoint;el.onfocus=()=>{if(el===num)checkpoint();};el.oninput=()=>{if(busy)return;const v=M.clamp(el.value,min,max,value);range.value=num.value=v;change(v);mark();preview();};}pair.append(range,num);wrap.append(pair);root.append(wrap);return pair;}
  function advanced(label,value,change){const box=section(label,()=>{},true),body=box.lastElementChild;within(body,()=>{const input=field('데이터 직접 편집',JSON.stringify(value,null,2),()=>{},'textarea');input.maxLength=8000000;input.spellcheck=false;input.onchange=()=>{try{const value=JSON.parse(input.value),old=snapshot();change(value);try{M.content(draft.game);}catch(e){draft=old.draft;images=new Map(old.images);draw();throw e;}mark();preview();}catch(e){status.textContent=e.message;status.dataset.error='true';}};});}
  function preview(){try{const oldURLs=previewURLs;previewURLs=[];const copy={...draft,assets:{},sounds:{...(draft.sounds||{})}};for(const [key,value]of images){const target=key.startsWith('sound:')?copy.sounds:copy.assets;if(value.path)target[key]=value;else if(value.blob){const url=URL.createObjectURL(value.blob);previewURLs.push(url);target[key]={...value,path:'',preview:url};}}G.setContent(copy);oldURLs.forEach(url=>URL.revokeObjectURL(url));}catch(e){status.textContent='편집 확인 · '+e.message;status.dataset.error='true';}}
  async function upload(key,file){if(!file)return false;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>20*1024*1024)throw Error('PNG·JPG·WEBP·GIF 파일을 20MB 이하로 올려 주세요');const bitmap=await createImageBitmap(file);const large=bitmap.width*bitmap.height>36000000;bitmap.close();if(large)throw Error('이미지가 너무 커요');checkpoint();images.set(key,{blob:file,transform:M.imageTransform()});return true;}
  function imageControls(label,key,setId){section(label,()=>{const file=n('input');file.type='file';file.accept='image/png,image/jpeg,image/webp,image/gif';file.setAttribute('aria-label',label+' 업로드');const uploadLabel=n('label','이미지 올리기 · 교체','wide');uploadLabel.append(file);root.append(uploadLabel);file.onchange=()=>run(async()=>{if(await upload(key,file.files[0])){setId(key);mark();preview();draw();}});const value=images.get(key);if(!value){root.append(n('p','아직 이미지가 없어요','small wide'));return;}const previewBox=n('div',undefined,'editor-image-thumb wide'),img=n('img');img.alt=label+' 미리보기';let url=value.blob?URL.createObjectURL(value.blob):A.imageURL(value.path);if(value.blob)previewURLs.push(url);img.src=url;const paint=()=>{const t=M.imageTransform(value.transform);img.style.transform=`translate(${t.x}%,${t.y}%) scale(${t.scale/100}) rotate(${t.rotate}deg)`;};paint();previewBox.append(img);root.append(previewBox);
    let moving;previewBox.style.touchAction='none';previewBox.onpointerdown=e=>{if(busy||e.button!==0)return;checkpoint();moving={x:e.clientX,y:e.clientY,t:M.imageTransform(value.transform)};previewBox.setPointerCapture(e.pointerId);e.preventDefault();};previewBox.onpointermove=e=>{if(!moving)return;const box=previewBox.getBoundingClientRect();value.transform=M.imageTransform({...moving.t,x:moving.t.x+(e.clientX-moving.x)/box.width*100,y:moving.t.y+(e.clientY-moving.y)/box.height*100});paint();};previewBox.onpointerup=previewBox.onpointercancel=e=>{if(!moving)return;moving=null;if(previewBox.hasPointerCapture(e.pointerId))previewBox.releasePointerCapture(e.pointerId);mark();preview();draw();};
    for(const [prop,text,min,max]of [['scale','이미지 크기',20,300],['x','이미지 X',-100,100],['y','이미지 Y',-100,100],['rotate','이미지 회전',-180,180]])slider(text,M.imageTransform(value.transform)[prop],v=>{value.transform={...M.imageTransform(value.transform),[prop]:v};paint();},min,max);
    button('가운데로 · 크기 초기화',()=>{checkpoint();value.transform=M.imageTransform();mark();preview();draw();});button('이미지 삭제',()=>{checkpoint();images.delete(key);delete draft.assets[key];setId('');mark();preview();draw();});
  });}
  function flagOptions(){const ids=new Set(Object.keys(draft.game.flagNames||{}));function scan(value){if(!value||typeof value!=='object')return;if(value.type==='flag'&&value.id)ids.add(value.id);for(const part of Object.values(value))if(part&&typeof part==='object')scan(part);}scan(draft.game.events);scan(draft.game.locations);return [...ids].map(id=>({id,name:draft.game.flagNames?.[id]||({'door-open':'현관문 열림','box-open':'상자 열림'})[id]||id}));}
  function makeFlag(){const id='flag-'+crypto.randomUUID();draft.game.flagNames||={};draft.game.flagNames[id]='새 진행 표시';return id;}
  function flagPicker(id,change){const options=flagOptions();if(id&&!options.some(o=>o.id===id))options.push({id,name:id});select('진행 표시',options,id,v=>{change(v);draw();});field('표시 이름',options.find(o=>o.id===id)?.name||'새 진행 표시',v=>{draft.game.flagNames||={};draft.game.flagNames[id]=v;});button('+ 새 진행 표시',()=>{checkpoint();change(makeFlag());mark();preview();draw();});}
  function conditions(list,apply){section('표시·실행 조건'+(list?.length?' · '+list.length+'개':''),()=>{for(const [index,c]of (list||[]).entries()){const row=n('div',undefined,'editor-row wide');root.append(row);within(row,()=>{select('조건 종류',[{id:'flag',name:'진행 표시'},{id:'item',name:'아이템 보유'},{id:'not-item',name:'아이템 미보유'},{id:'puzzle',name:'퍼즐 완료'},{id:'visit',name:'장소 방문'}],c.type,v=>{c.type=v;c.id=v==='visit'?draft.game.locations[0]?.id:v==='puzzle'?draft.game.puzzles[0]?.id:v.includes('item')?draft.game.items[0]?.id:(flagOptions()[0]?.id||makeFlag());draw();});if(c.type==='flag'){flagPicker(c.id,v=>c.id=v);field('조건 충족',c.value!==false,v=>c.value=v,'checkbox');}else select('조건 대상',c.type==='visit'?draft.game.locations:c.type==='puzzle'?draft.game.puzzles:draft.game.items,c.id,v=>c.id=v);if(['item','visit'].includes(c.type))field('필요 횟수·개수',c.count||1,v=>c.count=v,'number',1,999);button('조건 빼기',()=>{checkpoint();list.splice(index,1);mark();preview();draw();});});}button('+ 조건 추가',()=>{checkpoint();const next=list||[];next.push({type:'flag',id:flagOptions()[0]?.id||makeFlag(),value:true});apply(next);mark();preview();draw();});},true);}
  const stepTypes={say:'대사',choice:'선택지',give:'아이템 획득',take:'아이템 소모',collect:'콜렉션 등록',move:'장소 이동',world:'세계 이동',puzzle:'퍼즐 열기',goal:'목표 안내',flag:'진행 표시',actor:'캐릭터 연출',object:'조사 대상 표시',image:'이벤트 이미지',sfx:'효과음',wait:'잠깐 기다리기',dim:'화면 어둡게',shake:'화면 흔들기',chapter:'챕터 진행',complete:'퍼즐 완료 표시'};
  function newStep(type){const game=draft.game;switch(type){case 'say':return {type,speaker:'꿈뜰이',text:''};case 'choice':return {type,id:'choice-'+crypto.randomUUID(),options:[{text:'선택지 1',steps:[]},{text:'선택지 2',steps:[]}]};case 'give':case 'take':return {type,id:game.items[0]?.id||'',count:1};case 'move':case 'world':return {type,to:game.locations[0]?.id||''};case 'puzzle':case 'complete':return {type,id:game.puzzles[0]?.id||''};case 'collect':return {type,id:collectionOptions()[0]?.id||''};case 'chapter':return {type,id:draft.catalogue.chapters[0]?.id||'',cleared:false};case 'actor':return {type,id:game.characters[0]?.id||'',state:{visible:true}};case 'object':return {type,id:game.locations[0]?.objects?.[0]?.id||'',location:game.locations[0]?.id,visible:true};case 'flag':return {type,id:flagOptions()[0]?.id||makeFlag(),value:true};case 'goal':return {type,text:''};case 'wait':return {type,ms:500};case 'dim':return {type,opacity:.25,ms:300};case 'shake':return {type,strength:2,ms:300};case 'sfx':return {type,id:'bush'};case 'image':return {type,asset:'',visible:true};}}
  function stepList(steps,depth=0){if(depth>7){advanced('고급 분기 데이터',steps,v=>steps.splice(0,steps.length,...v));return;}steps.forEach((step,index)=>{const card=n('details',undefined,'editor-step wide');card.open=depth===0&&(focusedLines.get(activeId)||0)===index;card.ontoggle=()=>{if(card.open)focusedLines.set(activeId,index);};const summary=n('summary',String(index+1).padStart(2,'0')+' · '+(stepTypes[step.type]||step.type)+(step.type==='say'?' · '+(step.speaker||'꿈뜰이'):''));card.append(summary);const body=n('div',undefined,'editor-section-grid');card.append(body);root.append(card);within(body,()=>{section('동작 변경',()=>select('단계 종류',Object.entries(stepTypes).map(([id,name])=>({id,name})),step.type,v=>{const changed=newStep(v);if(step.condition)changed.condition=step.condition;steps[index]=changed;draw();}),true);if(step.type==='say'){speechFields(step,'대사 내용',()=>previewLine(step));}
    else if(step.type==='choice'){step.options.forEach((option,i)=>section('선택지 '+(i+1),()=>{field('선택지 문구',option.text,v=>option.text=v);if(step.options.length>2)button('이 선택지 빼기',()=>{checkpoint();step.options.splice(i,1);mark();preview();draw();});stepList(option.steps||=([]),depth+1);conditions(option.condition||[],v=>option.condition=v);},true));if(step.options.length<4)button('+ 선택지 추가',()=>{checkpoint();step.options.push({text:'새 선택지',steps:[]});mark();preview();draw();});}
    else if(['give','take'].includes(step.type)){select('아이템',draft.game.items,step.id,v=>step.id=v);field('개수',step.count||1,v=>step.count=v,'number',1,999);}
    else if(['move','world'].includes(step.type))select('이동할 장소',draft.game.locations,step.to,v=>step.to=v);
    else if(['puzzle','complete'].includes(step.type))select('퍼즐',draft.game.puzzles,step.id,v=>step.id=v);
    else if(step.type==='collect')select('등록할 콜렉션',collectionOptions(),step.id,v=>step.id=v);
    else if(step.type==='goal')field('지금 할 일',step.text||'',v=>step.text=v,'textarea');
    else if(step.type==='flag'){flagPicker(step.id,v=>step.id=v);field('완료·켜기',step.value!==false,v=>step.value=v,'checkbox');}
    else if(step.type==='actor'){select('캐릭터',draft.game.characters,step.id,v=>{step.id=v;draw();});step.state||={};field('캐릭터 표시',step.state.visible!==false,v=>step.state.visible=v,'checkbox');field('표정',step.state.emotion||'normal',v=>step.state.emotion=v);for(const [prop,label,min,max]of [['x','가로 위치',0,100],['y','세로 위치',0,100],['scale','크기 (%)',10,300]])field(label,step.state[prop]??(prop==='scale'?100:50),v=>step.state[prop]=v,'number',min,max);}
    else if(step.type==='object'){const loc=draft.game.locations.find(l=>l.id===step.location)||draft.game.locations[0];select('대상이 있는 장소',draft.game.locations,loc.id,v=>{step.location=v;step.id=draft.game.locations.find(l=>l.id===v).objects?.[0]?.id||'';draw();});select('조사 대상',loc.objects||[],step.id,v=>step.id=v);field('대상 표시',step.visible!==false,v=>step.visible=v,'checkbox');}
    else if(step.type==='image'){imageControls('이벤트 이미지',step.asset||'event:'+activeId+':'+(step.key||=(crypto.randomUUID())),v=>step.asset=v);field('이미지 표시',step.visible!==false,v=>step.visible=v,'checkbox');}
    else if(step.type==='sfx')select('효과음',[{id:'bush',name:'덤불 바스락'},{id:'house',name:'집 톡'}],step.id,v=>step.id=v);
    else if(step.type==='chapter'){select('챕터',draft.catalogue.chapters.map(c=>({id:c.id,name:c.title||'미공개 챕터'})),step.id,v=>step.id=v);field('챕터 클리어',step.cleared===true,v=>step.cleared=v,'checkbox');}
    if(['wait','dim','shake'].includes(step.type))field('시간 (밀리초)',step.ms??500,v=>step.ms=v,'number',0,30000);
    if(step.type==='dim')slider('어두운 정도 (%)',Math.round((step.opacity??.25)*100),v=>step.opacity=v/100,0,80);
    if(step.type==='shake')slider('흔들림 강도',step.strength??2,v=>step.strength=v,0,10);
    conditions(step.condition||[],v=>step.condition=v);
    const actions=n('div',undefined,'editor-row-actions wide');root.append(actions);const up=button('위로',()=>{checkpoint();[steps[index-1],steps[index]]=[steps[index],steps[index-1]];mark();preview();draw();},actions);up.disabled=index===0;const down=button('아래로',()=>{checkpoint();[steps[index+1],steps[index]]=[steps[index],steps[index+1]];mark();preview();draw();},actions);down.disabled=index===steps.length-1;button('복제',()=>{checkpoint();const copy=structuredClone(step);if(copy.type==='choice')copy.id='choice-'+crypto.randomUUID();if(copy.type==='image'){copy.key=crypto.randomUUID();const oldKey=step.asset||'event:'+activeId+':'+step.key,newKey='event:'+activeId+':'+copy.key;if(images.has(oldKey)){images.set(newKey,structuredClone(images.get(oldKey)));copy.asset=newKey;}}steps.splice(index+1,0,copy);mark();preview();draw();});button('이 단계 삭제',()=>{checkpoint();steps.splice(index,1);mark();preview();draw();});});});sequenceActions(steps,false);}
  function objects(rec){section('조사할 대상',()=>{rec.objects||=[];if(rec.objects.length){const o=rec.objects.find(o=>o.id===selectedObject)||rec.objects[0];selectedObject=o.id;const picker=select('클릭 영역 대상',rec.objects,o.id,v=>{selectedObject=v;draw();});picker.onchange=()=>{selectedObject=picker.value;draw();};field('대상 이름',o.name,v=>o.name=v);select('클릭하면',[{id:'inspect',name:'조사하기'},{id:'talk',name:'말 걸기'},{id:'use',name:'아이템 사용·조사'},{id:'move',name:'장소로 이동'}],o.kind,v=>{o.kind=v;if(v==='move'&&!o.to)o.to=draft.game.locations[0]?.id;draw();});if(o.kind==='move')select('이동할 장소',draft.game.locations,o.to,v=>o.to=v);else {select('연결할 대화·이벤트',eventOptions(),o.event||'',v=>o.event=v,true);select('다시 조사할 때',eventOptions(),o.repeat?.[0]||'',v=>{o.repeat=v?[v,...(o.repeat||[]).slice(1)]:[];},true);}for(const [prop,label]of [['x','영역 X'],['y','영역 Y'],['w','영역 너비'],['h','영역 높이']])slider(label,o.rect?.[prop]??10,v=>{o.rect=M.rect({...o.rect,[prop]:v});},['w','h'].includes(prop)?1:0,100);field('빈 영역 안내 표시',o.placeholder===true,v=>o.placeholder=v,'checkbox');conditions(o.condition||[],v=>o.condition=v);section('아이템 사용 연결',()=>{o.use||={};for(const [id,use]of Object.entries(o.use))section(draft.game.items.find(i=>i.id===id)?.name||id,()=>{select('사용 후 대화·이벤트',eventOptions(),use.event,v=>use.event=v,true);field('아이템 소모',use.consume===true,v=>use.consume=v,'checkbox');button('사용 연결 빼기',()=>{checkpoint();delete o.use[id];mark();preview();draw();});});const remaining=draft.game.items.filter(i=>!Object.hasOwn(o.use,i.id));if(remaining.length){let item=remaining[0].id;const add=select('연결할 아이템',remaining,item,v=>item=v);add.onchange=()=>item=add.value;button('+ 아이템 연결',()=>{checkpoint();o.use[item]={event:'',consume:false};mark();preview();draw();});}},true);advanced('고급 · 선택한 대상 데이터',o,v=>Object.assign(o,v));}
    button('+ 조사 대상 추가',()=>{checkpoint();const o={id:'object-'+crypto.randomUUID(),name:'새 조사 대상',kind:'inspect',rect:{x:40,y:40,w:15,h:15},event:'',condition:[]};rec.objects.push(o);selectedObject=o.id;mark();preview();draw();});
  },true);}
  function actors(rec){section('등장인물 배치',()=>{rec.actors||=[];if(rec.actors.length){const actor=rec.actors.find(a=>a.id===selectedActor)||rec.actors[0];selectedActor=actor.id;const picker=select('배치할 캐릭터',rec.actors.map(a=>({id:a.id,name:draft.game.characters.find(c=>c.id===a.id)?.name||a.id})),actor.id,v=>{selectedActor=v;draw();});picker.onchange=()=>{selectedActor=picker.value;draw();};for(const [prop,label,min,max]of [['x','캐릭터 X',0,100],['y','캐릭터 Y',0,100],['scale','캐릭터 크기',10,300],['rotate','캐릭터 회전',-180,180],['z','캐릭터 표시 순서',0,50]])slider(label,actor[prop]??(prop==='scale'?100:prop==='z'?10:0),v=>actor[prop]=v,min,max);field('캐릭터 표시',actor.visible!==false,v=>actor.visible=v,'checkbox');field('좌우 반전',actor.flip===true,v=>actor.flip=v,'checkbox');const c=draft.game.characters.find(c=>c.id===actor.id);select('표정',[...new Set(['normal',...Object.keys(c?.images||{})])].map(id=>({id,name:id==='normal'?'기본':(c?.emotionNames?.[id]||id)})),actor.emotion||'normal',v=>actor.emotion=v);conditions(actor.condition||[],v=>actor.condition=v);button('이 장소에서 빼기',()=>{checkpoint();rec.actors=rec.actors.filter(a=>a!==actor);selectedActor='';mark();preview();draw();});}const remaining=draft.game.characters.filter(c=>!rec.actors.some(a=>a.id===c.id));if(remaining.length){let id=remaining[0].id;const picker=select('추가할 인물',remaining,id,v=>id=v);picker.onchange=()=>id=picker.value;button('+ 인물 배치',()=>{checkpoint();rec.actors.push({id,x:50,y:85,scale:70,visible:true,emotion:'normal',condition:[]});selectedActor=id;mark();preview();draw();});}},true);}
  function exits(rec){section('장소 이동 연결',()=>{rec.exits||=[];for(const [i,exit]of rec.exits.entries())section(exit.label||'이동 '+(i+1),()=>{field('버튼 이름',exit.label,v=>exit.label=v);select('이동할 장소',draft.game.locations,exit.to,v=>exit.to=v);select('화살표 위치',[{id:'left',name:'왼쪽'},{id:'right',name:'오른쪽'}],exit.side||'right',v=>exit.side=v);conditions(exit.condition||[],v=>exit.condition=v);button('이동 연결 빼기',()=>{checkpoint();rec.exits.splice(i,1);mark();preview();draw();});});button('+ 이동 연결 추가',()=>{checkpoint();rec.exits.push({id:'exit-'+crypto.randomUUID(),label:'이동하기',to:draft.game.locations[0]?.id,side:'right',condition:[]});mark();preview();draw();});},true);}


  function paletteEditor(rec){section('캐릭터 고유 자막 색상',()=>{rec.subtitleStyle=T.style(rec.subtitleStyle,rec.id);const swatch=n('span',rec.name,'member-palette-preview wide');const paint=()=>{for(const k of ['accent','soft','text'])swatch.style.setProperty('--swatch-'+k,rec.subtitleStyle[k]);};paint();root.append(swatch);for(const [key,label]of [['accent','고유색'],['soft','연한 보조색'],['text','자막 글자색']])field(label,rec.subtitleStyle[key],v=>{rec.subtitleStyle[key]=v;paint();},'color');button('기본 색상으로',()=>{checkpoint();rec.subtitleStyle=T.style(null,rec.id);mark();preview();draw();});},true);}
  function previewLine(line){M.content(draft.game);preview();dialog.close();G.testDialogue([{type:'say',...line}],previewLocation||G.getState()?.location||draft.game.start,activeKind==='events'?activeId:undefined);}
  function speechFields(line,label,onTest){const character=T.character(draft.game,line);select('화자',[{id:'',name:'직접 이름 입력'},...draft.game.characters],line.actor||character?.id||'',v=>{if(v){line.actor=v;line.speaker=draft.game.characters.find(c=>c.id===v).name;}else delete line.actor;draw();});field('이름표 표시',line.speaker||character?.name||'꿈뜰이',v=>line.speaker=v);select('표시 방식',[{id:'dialogue',name:'양피지 대화창'},{id:'monologue',name:'중앙 독백'},{id:'reaction',name:'짧은 리액션'}],line.delivery||(activeKind==='monologue'?'monologue':'dialogue'),v=>line.delivery=v);if(line.actor){const c=draft.game.characters.find(c=>c.id===line.actor);select('표정',[...new Set(['normal',...Object.keys(c?.images||{})])].map(id=>({id,name:id==='normal'?'기본':c?.emotionNames?.[id]||id})),line.emotion||'normal',v=>line.emotion=v);}field(label,line.text,v=>{line.text=v;if(activeKind==='monologue'){const rec=entries().find(r=>r.id===activeId);if(rec?.lines[0]===line)rec.text=v;}},'textarea');root.append(n('p','긴 글도 같은 줄에 입력해 주세요 · 화면에서는 크기를 유지하며 나눠 보여요','small wide'));button('현재 대사 미리보기',onTest);captionFields(line);}
  function captionFields(line){const wrapper=section('자막 연출 설정',()=>{field('추가 말풍선 사용',line.caption?.enabled===true,v=>{line.caption=v?T.caption({enabled:true,text:'',actor:line.actor||'',kind:'bubble',animation:'fade'}):null;draw();},'checkbox');if(!line.caption?.enabled)return;const c=line.caption;field('말풍선 문구',c.text,v=>c.text=v,'textarea').maxLength=120;select('말풍선 종류',[{id:'bubble',name:'일반 강조'},{id:'thought',name:'속마음'},{id:'surprise',name:'놀람'},{id:'quiet',name:'정적'},{id:'subtitle',name:'간단한 강조 자막'}],c.kind,v=>c.kind=v);select('연결할 캐릭터',[{id:'',name:'현재 화자'},...draft.game.characters],c.actor||'',v=>c.actor=v);select('말풍선 위치',[{id:'auto',name:'캐릭터 근처 · 자동'},{id:'manual',name:'직접 지정'}],c.position,v=>{c.position=v;draw();});if(c.position==='manual'){slider('말풍선 X (%)',c.x,v=>c.x=v,0,100);slider('말풍선 Y (%)',c.y,v=>c.y=v,0,100);}slider('말풍선 글자 크기',c.size,v=>c.size=v,18,48);select('등장 애니메이션',[{id:'none',name:'없음'},{id:'fade',name:'부드럽게 등장'},{id:'pop',name:'살짝 확대'}],c.animation,v=>c.animation=v);
 section('필요할 때만 · 색상·표시 시간·소리',()=>{const character=T.character(draft.game,{actor:c.actor||line.actor,speaker:line.speaker}),palette=T.style(character?.subtitleStyle,character?.id);for(const [prop,key,label]of [['textColor','text','말풍선 글자색'],['borderColor','accent','말풍선 테두리색'],['background','soft','말풍선 배경색']])field(label,c[prop]||palette[key],v=>c[prop]=v,'color');button('캐릭터 고유색 자동 적용',()=>{checkpoint();delete c.textColor;delete c.borderColor;delete c.background;mark();preview();draw();});field('표시 시간 (밀리초)',c.duration,v=>c.duration=v,'number',500,15000);field('등장 대기 (밀리초)',c.delay,v=>c.delay=v,'number',0,5000);field('다음 대사에도 잠깐 유지',c.persist,v=>c.persist=v,'checkbox');select('캐릭터·이미지 앞뒤',[{id:'front',name:'앞에 표시'},{id:'back',name:'뒤에 표시'}],c.order,v=>c.order=v);soundFields(c);},true);
 },true);wrapper.open=line.caption?.enabled===true;}
 function soundFields(c){const sounds=[...images].filter(([key])=>key.startsWith('sound:')).map(([id,value])=>({id,name:value.name||'효과음'}));select('자막 효과음',[{id:'',name:'없음'},...sounds],c.sound||'',v=>c.sound=v);const file=n('input');file.type='file';file.accept='audio/mpeg,audio/ogg,audio/wav,audio/mp4';file.setAttribute('aria-label','자막 효과음 업로드');const label=n('label','효과음 파일 추가 · 10MB 이하','wide');label.append(file);root.append(label);file.onchange=()=>run(()=>transaction(async()=>{const f=file.files[0];if(!f)return;if(!['audio/mpeg','audio/ogg','audio/wav','audio/x-wav','audio/mp4'].includes(f.type)||f.size>10*1024*1024)throw Error('MP3·OGG·WAV·M4A 파일을 10MB 이하로 올려 주세요');checkpoint();const key='sound:'+crypto.randomUUID();images.set(key,{blob:f,name:f.name});c.sound=key;mark();preview();draw();}));const listen=button('연결 효과음 미리듣기',()=>{const value=images.get(c.sound);if(!value)return;const url=value.blob?URL.createObjectURL(value.blob):'/api/sound?path='+encodeURIComponent(value.path),audio=new Audio(url);audio.volume=PixelySettings.getVolume('effects');audio.onended=()=>{if(value.blob)URL.revokeObjectURL(url);};void audio.play().catch(()=>G.notify('효과음을 재생하지 못했어요'));});listen.disabled=!c.sound;}
 function appendLine(list,delivery,insert=list.length,done=()=>{}){if(list.length>=300)throw Error('한 흐름에는 300줄까지 이어 쓸 수 있어요');checkpoint();const previous=list.slice(0,insert).reverse().find(l=>l.type==='say'||!l.type),actor=delivery==='monologue'?'player':previous?.actor||'player';const line={type:'say',id:undefined,speaker:draft.game.characters.find(c=>c.id===actor)?.name||previous?.speaker||'꿈뜰이',actor,delivery,text:''};delete line.id;if(activeKind==='monologue'){delete line.type;line.id='line-'+crypto.randomUUID();}if(delivery==='reaction')line.caption=T.caption({text:'',enabled:true,kind:'quiet',animation:'fade',actor});list.splice(insert,0,line);focusedLines.set(activeId,insert);done();mark();preview();draw();}
 function lineActions(list,index,done=()=>{}){const actions=n('div',undefined,'editor-row-actions wide');root.append(actions);const up=button('위로',()=>{checkpoint();[list[index-1],list[index]]=[list[index],list[index-1]];focusedLines.set(activeId,index-1);done();mark();preview();draw();},actions);up.disabled=index===0;const down=button('아래로',()=>{checkpoint();[list[index+1],list[index]]=[list[index],list[index+1]];focusedLines.set(activeId,index+1);done();mark();preview();draw();},actions);down.disabled=index===list.length-1;button('바로 아래 이어쓰기',()=>appendLine(list,list[index].delivery||'monologue',index+1,done),actions);const remove=button('이 줄 삭제',()=>{checkpoint();list.splice(index,1);focusedLines.set(activeId,Math.max(0,index-1));done();mark();preview();draw();},actions);remove.disabled=list.length===1;}
 function sequenceActions(list,mono,done=()=>{}){const actions=n('div',undefined,'editor-sequence-actions wide');root.append(actions);button(mono?'+ 독백 이어쓰기':'+ 대사 이어쓰기',()=>appendLine(list,mono?'monologue':'dialogue',list.length,done),actions);button('+ 멤버 대사 추가',()=>appendLine(list,'dialogue',list.length,done),actions);button('+ 리액션 추가',()=>appendLine(list,'reaction',list.length,done),actions);if(!mono)button('+ 잠깐 쉬기',()=>{checkpoint();list.push({type:'wait',ms:800});focusedLines.set(activeId,list.length-1);mark();preview();draw();},actions);
 if(!mono)section('이벤트 동작 추가',()=>{let kind='choice';const picker=select('추가할 동작',Object.entries(stepTypes).filter(([id])=>id!=='say').map(([id,name])=>({id,name})),kind,v=>kind=v);picker.onchange=()=>kind=picker.value;button('+ 동작 추가',()=>{checkpoint();list.push(newStep(kind));focusedLines.set(activeId,list.length-1);mark();preview();draw();});},true);section('여러 대사 한 번에 이어 붙이기',()=>{const text=field('대사 한꺼번에 입력','',()=>{},'textarea');text.maxLength=50000;text.onchange=()=>{};root.append(n('p','화자 이름: 대사 형식으로 붙여넣기 · 이름 없는 다음 줄은 앞 대사에 이어져요','small wide'));button('현재 흐름에 추가',()=>{const rows=T.parseSequence(text.value,draft.game.characters,{speaker:'꿈뜰이',actor:'player',delivery:mono?'monologue':'dialogue'});if(!rows.length)return;if(rows.length+list.length>300)throw Error('한 흐름에는 300줄까지 등록할 수 있어요');checkpoint();if(mono)for(const row of rows){delete row.type;row.id='line-'+crypto.randomUUID();}focusedLines.set(activeId,list.length);list.push(...rows);done();mark();preview();draw();});},true);}

  function imageLayers(rec,records){rec.layers||=[];
    section('이미지 레이어 · 아래 항목일수록 앞에 보여요',()=>{const file=n('input');file.type='file';file.multiple=true;file.accept='image/png,image/jpeg,image/webp,image/gif';file.setAttribute('aria-label','이미지 레이어 추가');const label=n('label','+ 이미지 계속 추가 · 여러 장 선택 가능','wide');label.append(file);root.append(label);file.onchange=()=>run(()=>transaction(async()=>{const files=[...file.files];if(rec.layers.length+files.length>100)throw Error('장면당 이미지는 100개까지 추가할 수 있어요');const old=snapshot();try{for(const f of files){const id='layer-'+crypto.randomUUID(),key='event:layer:'+id;if(await upload(key,f)){rec.layers.push({id,name:f.name.slice(0,100),asset:key,visible:true,opacity:100,fit:'contain',animation:'none',duration:6,amount:10,delay:0});selectedLayer=id;}}mark();preview();draw();}catch(e){restore(old);throw e;}}));
      const list=n('div',undefined,'monologue-layer-list wide');root.append(list);const selected=rec.layers.find(l=>l.id===selectedLayer)||rec.layers.at(-1);selectedLayer=selected?.id||'';
      rec.layers.forEach((layer,index)=>{const row=n('div',undefined,'monologue-layer-row');row.setAttribute('aria-current',String(layer.id===selectedLayer));list.append(row);button((index+1)+' · '+layer.name+(layer.visible?'':' · 숨김'),()=>{selectedLayer=layer.id;draw();},row);const back=button('뒤로',()=>{checkpoint();[rec.layers[index-1],rec.layers[index]]=[rec.layers[index],rec.layers[index-1]];mark();preview();draw();},row);back.disabled=index===0;const front=button('앞으로',()=>{checkpoint();[rec.layers[index+1],rec.layers[index]]=[rec.layers[index],rec.layers[index+1]];mark();preview();draw();},row);front.disabled=index===rec.layers.length-1;});
      if(!selected){root.append(n('p','이미지를 올리면 레이어가 여기에 차곡차곡 쌓여요','small wide'));return;}
      select('이미지 앞뒤',[{id:'back',name:'캐릭터 뒤'},{id:'front',name:'캐릭터 앞'}],selected.plane||'front',v=>selected.plane=v);select('연결할 캐릭터',[{id:'',name:'연결 안 함'},...draft.game.characters],selected.actor||'',v=>selected.actor=v);field('레이어 이름',selected.name,v=>selected.name=v);field('이 레이어 보이기',selected.visible,v=>selected.visible=v,'checkbox');select('이미지 채우기',[{id:'contain',name:'이미지 전체 보이기'},{id:'cover',name:'화면 가득 채우기'}],selected.fit,v=>selected.fit=v);slider('레이어 불투명도',selected.opacity,v=>selected.opacity=v,0,100);
      imageControls('선택한 레이어',selected.asset||'event:layer:'+selected.id,id=>selected.asset=id);
      section('애니메이션',()=>{select('애니메이션',[{id:'none',name:'움직임 없음'},{id:'float',name:'살짝 떠오르기'},{id:'sway',name:'좌우로 흔들기'},{id:'breathe',name:'천천히 커졌다 작아지기'},{id:'drift',name:'좌우로 떠다니기'},{id:'fade',name:'부드럽게 나타나기'}],selected.animation,v=>selected.animation=v);slider('움직임 강도',selected.amount,v=>selected.amount=v,0,80);slider('움직임 시간 (초)',selected.duration,v=>selected.duration=v,1,30);slider('시작 지연 (초)',selected.delay,v=>selected.delay=v,0,10);});
      button('레이어 복제',()=>{checkpoint();const copy=structuredClone(selected);copy.id='layer-'+crypto.randomUUID();copy.name=(copy.name+' 복사').slice(0,100);const key='event:layer:'+copy.id;if(images.has(selected.asset))images.set(key,structuredClone(images.get(selected.asset)));copy.asset=images.has(key)?key:'';rec.layers.splice(rec.layers.indexOf(selected)+1,0,copy);selectedLayer=copy.id;mark();preview();draw();});
      button('레이어 삭제',()=>{checkpoint();rec.layers.splice(rec.layers.indexOf(selected),1);const used=JSON.stringify(draft.game).includes(JSON.stringify(selected.asset));if(!used){images.delete(selected.asset);delete draft.assets[selected.asset];}selectedLayer='';mark();preview();draw();});
    });
  }
  function monologue(rec){const config=draft.game.monologue;viewTabs([['text','대사'],['layers','이미지 레이어'],['settings','장면 설정']]);
    if(editorView==='text')section('같은 장면에서 이어지는 독백·대사',()=>{rec.lines||=PixelyMonologue.lines(rec);rec.lines.forEach((line,index)=>{const row=n('details',undefined,'editor-step wide');row.open=(focusedLines.get(rec.id)||0)===index;row.ontoggle=()=>{if(row.open)focusedLines.set(rec.id,index);};row.append(n('summary',(index+1)+' · '+(line.speaker||'꿈뜰이')+' · '+(line.text.slice(0,24)||'내용 입력'),'editor-line-summary'));const body=n('div',undefined,'editor-section-grid');row.append(body);root.append(row);within(body,()=>{speechFields(line,'독백 대사',()=>{preview();dialog.close();G.testMonologue(config.pages.indexOf(rec),index);});lineActions(rec.lines,index,()=>rec.text=rec.lines[0].text);});});sequenceActions(rec.lines,true,()=>rec.text=rec.lines[0].text);button('이 독백 미리보기',()=>test(rec));});
    if(editorView==='layers')imageLayers(rec,config.pages);
    if(editorView==='settings'){
    section('독백 화면 설정',()=>{field('게임 시작할 때 독백 표시',config.enabled,v=>config.enabled=v,'checkbox');const color=field('독백 배경색',config.background,v=>config.background=v,'color');color.classList.add('monologue-color');slider('대사 세로 위치 (%)',config.textY,v=>config.textY=v,20,85);slider('대사 영역 너비 (%)',config.textWidth,v=>config.textWidth=v,40,90);},true);
    section('다른 배경 장면 · 순서 관리',()=>{field('장면 이름',rec.name,v=>rec.name=v);button('+ 새 배경 장면',create);const index=config.pages.indexOf(rec);const previous=button('이 장면 먼저',()=>{checkpoint();[config.pages[index-1],config.pages[index]]=[config.pages[index],config.pages[index-1]];mark();preview();draw();});previous.disabled=index===0;const next=button('이 장면 나중에',()=>{checkpoint();[config.pages[index+1],config.pages[index]]=[config.pages[index],config.pages[index+1]];mark();preview();draw();});next.disabled=index===config.pages.length-1;const remove=button('이 독백 장면 삭제',()=>{checkpoint();config.pages.splice(index,1);for(const l of rec.layers)if(!config.pages.some(p=>p.layers.some(other=>other.asset===l.asset))){images.delete(l.asset);delete draft.assets[l.asset];}activeId='';mark();preview();draw();});remove.disabled=config.pages.length===1;},true);}
  }

  function viewTabs(views){if(!views.some(v=>v[0]===editorView))editorView=views[0][0];const nav=n('nav',undefined,'editor-view-tabs');nav.setAttribute('aria-label','편집 내용');root.append(nav);for(const [id,label]of views){const b=button(label,()=>{editorView=id;draw();},nav);b.setAttribute('aria-pressed',String(editorView===id));}}
  function removeRecord(rec){const copy=structuredClone(draft);if(activeKind==='events'){delete copy.game.events[rec.id];delete copy.game.eventLayers?.[rec.id];delete copy.game.eventNames?.[rec.id];}else copy.game[activeKind]=copy.game[activeKind].filter(r=>r.id!==rec.id);try{M.content(copy.game);}catch(e){throw Error('사용 중인 연결을 먼저 바꿔 주세요 · '+e.message);}checkpoint();draft=copy;activeId='';mark();preview();draw();}
  function draw(){root=formRoot;root.replaceChildren();if(!draft)return;const records=entries(),rec=records.find(r=>r.id===activeId)||records[0];if(rec){activeId=rec.id;const picker=select('항목',records.map(r=>({id:r.id,name:recordName(r)})),rec.id,v=>{activeId=v;selectedObject=selectedActor='';draw();});picker.onchange=()=>{activeId=picker.value;selectedObject=selectedActor='';draw();};}if(activeKind!=='monologue')button('+ '+names[activeKind]+' 추가',create);if(!rec){root.append(n('p','아직 항목이 없어요 · 위에서 추가해 주세요','wide'));controls();return;}
    if(activeKind==='monologue'){monologue(rec);}
    else if(activeKind==='events'){field('이벤트 이름',eventName(rec.id),v=>{draft.game.eventNames||={};draft.game.eventNames[rec.id]=v;});const place=select('미리보기 장소',draft.game.locations,previewLocation||draft.game.start,v=>previewLocation=v);place.onchange=()=>previewLocation=place.value;viewTabs([['text','대사'],['layers','이미지 레이어']]);if(editorView==='layers'){draft.game.eventLayers||={};const holder={layers:draft.game.eventLayers[rec.id]||=[]};imageLayers(holder,Object.values(draft.game.eventLayers).map(layers=>({layers})));}else section('한곳에서 이어지는 대사·리액션',()=>stepList(rec.steps));button('이 이벤트 테스트',()=>test(rec));advanced('고급 · 이벤트 데이터',rec.steps,v=>draft.game.events[rec.id]=v);}
    else {field('이름',rec.name||rec.title||'',v=>{if(activeKind==='puzzles')rec.title=v;else rec.name=v;});if(activeKind==='locations'){viewTabs([['text','장소·조사'],['layers','이미지 레이어']]);if(editorView==='layers')imageLayers(rec,draft.game.locations);else {imageControls('장소 배경',rec.background||'scene:'+rec.id+':background',id=>rec.background=id);select('기존 배경',[{id:'house',name:'기존 집 앞'},{id:'blank',name:'빈 공간'}],rec.builtin||'blank',v=>rec.builtin=v);select('입장할 때 대화·이벤트',eventOptions(),rec.enter||'',v=>rec.enter=v,true);objects(rec);actors(rec);exits(rec);button('이 장면 테스트',()=>test(rec));advanced('고급 · 장소 데이터',rec,v=>Object.assign(rec,v));}}
      else if(activeKind==='characters'){paletteEditor(rec);select('말 걸었을 때',eventOptions(),rec.talk||'',v=>rec.talk=v,true);rec.images||={};const emotions=[...new Set(['normal',...Object.keys(rec.images)])];let emotion=editingEmotions.get(rec.id)||'normal';if(!emotions.includes(emotion))emotions.push(emotion);const picker=select('편집할 표정',emotions.map(id=>({id,name:id==='normal'?'기본':(rec.emotionNames?.[id]||id)})),emotion,v=>{editingEmotions.set(rec.id,v);draw();});picker.onchange=()=>{editingEmotions.set(rec.id,picker.value);draw();};imageControls('표정 이미지 · '+(rec.emotionNames?.[emotion]|| (emotion==='normal'?'기본':emotion)),rec.images[emotion]||'character:'+rec.id+':'+emotion,id=>{if(id)rec.images[emotion]=id;else delete rec.images[emotion];});section('표정 추가',()=>{let label='';const input=field('새 표정 이름','',v=>label=v);input.onchange=()=>label=input.value;button('+ 표정 추가',()=>{if(!label.trim())throw Error('표정 이름을 적어 주세요');checkpoint();const id='emotion-'+crypto.randomUUID();rec.images[id]='';rec.emotionNames||={};rec.emotionNames[id]=label.trim();editingEmotions.set(rec.id,id);mark();preview();draw();});},true);}
      else if(activeKind==='items'){field('설명',rec.description||'',v=>rec.description=v,'textarea');select('콜렉션에 함께 등록',collectionOptions(),rec.collection||'',v=>rec.collection=v,true);imageControls('아이템 이미지',rec.image||'item:'+rec.id,id=>rec.image=id);}
      else if(activeKind==='puzzles'){field('문제',rec.question||'',v=>rec.question=v,'textarea');field('정답',rec.answer||'',v=>rec.answer=v);select('정답 후 대화·이벤트',eventOptions(),rec.success||'',v=>rec.success=v,true);}
    }
    if(activeKind!=='monologue'||editorView==='settings')section('시작·자동 저장 설정',()=>{select('시작 장소',draft.game.locations,draft.game.start,v=>draft.game.start=v);select('처음 시작할 대화',eventOptions(),draft.game.opening||'',v=>draft.game.opening=v,true);draft.game.autosave||={};for(const [key,label]of [['event','이벤트 후 저장'],['move','이동 후 저장'],['puzzle','퍼즐 후 저장'],['chapter','챕터 후 저장']])field(label,draft.game.autosave[key]!==false,v=>draft.game.autosave[key]=v,'checkbox');},true);if(activeKind!=='monologue')section('항목 삭제',()=>button('이 항목 삭제',()=>removeRecord(rec)).classList.add('editor-danger'),true);controls();if(busy)root.querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=true);}
  function create(){checkpoint();const id=(activeKind==='events'?'event':activeKind.slice(0,-1))+'-'+crypto.randomUUID();if(activeKind==='monologue'){if(draft.game.monologue.pages.length>=100)throw Error('독백 장면은 100개까지 만들 수 있어요');draft.game.monologue.pages.push({id,name:'새 독백',text:'',lines:[{id:'line-'+crypto.randomUUID(),speaker:'꿈뜰이',actor:'player',delivery:'monologue',text:''}],layers:[]});}else if(activeKind==='events'){draft.game.events[id]=[{type:'say',speaker:'꿈뜰이',text:''}];draft.game.eventNames||={};draft.game.eventNames[id]='새 대화';}else draft.game[activeKind].push(activeKind==='locations'?{id,name:'새 장소',builtin:'blank',actors:[],objects:[],exits:[]}:activeKind==='characters'?{id,name:'새 캐릭터',images:{}}:activeKind==='puzzles'?{id,title:'새 퍼즐',question:'',answer:'',success:''}:{id,name:'새 아이템',description:'',image:''});activeId=id;selectedActor=selectedObject='';mark();preview();draw();}
  function test(rec){M.content(draft.game);preview();dialog.close();if(!G.getState())G.testStart();if(activeKind==='monologue')G.testMonologue(draft.game.monologue.pages.indexOf(rec));else if(activeKind==='locations')G.testScene(rec.id);else {G.testDialogue(rec.steps,previewLocation||G.getState()?.location||draft.game.start,activeKind==='events'?activeId:undefined);}G.notify('테스트 중 · 일반 플레이 기록에는 저장되지 않아요');}
  async function save(){M.content(draft.game);showStatus('서버에 저장 중…');const prepared=await A.prepare(draft,images),result=await A.save(prepared,base);draft=result;base=result.revision;images=new Map([...Object.entries(result.assets),...Object.entries(result.sounds||{})]);dirty=false;await cache();preview();draw();showStatus('저장 완료 · 미리보기 후 사이트에 반영해 주세요');}
  async function transaction(fn){if(busy)return;busy=true;const disabled=[...dialog.querySelectorAll('button,input,select,textarea')].map(el=>[el,el.disabled]);disabled.forEach(([el])=>el.disabled=true);try{await fn();}finally{busy=false;disabled.forEach(([el,value])=>el.disabled=value);draw();controls();}}
  const undoButton=button('되돌리기',()=>{if(!past.length)return;future.push(snapshot());restore(past.pop());void cache();},tools),redoButton=button('다시 실행',()=>{if(!future.length)return;past.push(snapshot());restore(future.pop());void cache();},tools);
  button('저장',()=>transaction(save),tools).dataset.save='';
  button('미리보기',()=>{M.content(draft.game);preview();dialog.close();if(!G.getState())G.testStart();if(activeKind==='monologue')G.testMonologue(draft.game.monologue.pages.findIndex(p=>p.id===activeId));else if(activeKind==='events')G.testDialogue(draft.game.events[activeId],previewLocation||draft.game.start,activeId);else G.testScene(activeKind==='locations'?activeId:G.getState()?.location||draft.game.start);G.notify('미리보기 · 편집 버튼으로 돌아갈 수 있어요');},tools);
  const publishButton=button('사이트에 반영',()=>transaction(async()=>{if(dirty||base==='initial')await save();await A.publish(base);showStatus('사이트 반영 완료 · 일반 화면에서도 확인할 수 있어요');}),tools);publishButton.classList.add('primary');
  const dragButton=button('화면에서 위치 조절',()=>{M.content(draft.game);preview();if(!G.getState())G.testStart();G.testScene(activeKind==='locations'?activeId:G.getState()?.location||draft.game.start);dragEnabled=true;document.getElementById('play-screen').classList.add('hitboxes');dialog.close();G.pause(true);dragBar.hidden=false;G.notify('조사 영역·캐릭터를 드래그한 뒤 조절 완료');},tools);
  for(const [group,kinds]of [['이야기',['monologue','events']],['무대',['locations','characters']],['게임',['items','puzzles']]]){const groupEl=n('div',undefined,'editor-tab-group');groupEl.append(n('span',group));tabs.append(groupEl);for(const kind of kinds){const label=names[kind];const b=button(label,()=>{activeKind=kind;editorView='text';activeId='';selectedActor=selectedObject='';draw();},groupEl);b.dataset.kind=kind;}}
  const dragBar=n('div',undefined,'editor-drag-bar');dragBar.hidden=true;dragBar.append(n('span','조사 영역·캐릭터를 끌어서 배치'));button('조절 완료',()=>{dragEnabled=false;dragBar.hidden=true;document.getElementById('play-screen').classList.remove('hitboxes');G.pause(false);void open();},dragBar);document.body.append(dragBar);
  async function open(){await G.ready;if(!A.isEditor())return;if(!draft){const server=await A.request('draft'),local=await cached();if(local?.dirty&&local.base===server.revision){draft=local.draft;images=new Map(local.images);base=local.base;dirty=true;}else {draft=server;images=new Map([...Object.entries(server.assets),...Object.entries(server.sounds||{})]);base=server.revision;}}draft.game=M.content(draft.game);dragEnabled=false;dragBar.hidden=true;document.getElementById('play-screen').classList.remove('hitboxes');G.pause(false);preview();showStatus();draw();if(!dialog.open)dialog.showModal();}
  launch.onclick=G.safeAction(open);dialog.querySelector('[data-close]').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
  function mode(){launch.hidden=!A.isEditor();if(!A.isEditor()){if(dialog.open)dialog.close();dragEnabled=false;dragBar.hidden=true;document.getElementById('play-screen').classList.remove('hitboxes');G.pause(false);}}
  A.beforeLeave?.(()=>cacheChain);dialog.addEventListener('close',()=>G.renderScene());A.ready.then(mode);addEventListener('pixely:developer-mode',mode);G.ready.then(()=>{if(new URLSearchParams(location.search).get('edit')==='1'){if(A.isEditor())void run(open);else void A.loginOpen();}});
  let drag;const screen=document.getElementById('play-screen');screen.addEventListener('pointerdown',e=>{if(e.button!==0||!dragEnabled||!A.isEditor()||!draft)return;const el=e.target.closest('[data-object],[data-actor]');if(!el)return;const location=draft.game.locations.find(l=>l.id===G.getState()?.location),record=el.dataset.object?location?.objects.find(o=>o.id===el.dataset.object):location?.actors.find(a=>a.id===el.dataset.actor);if(!record)return;checkpoint();drag={record,el,x:e.clientX,y:e.clientY,startX:record.rect?.x??record.x,startY:record.rect?.y??record.y,rect:!!record.rect};el.setPointerCapture(e.pointerId);e.preventDefault();e.stopImmediatePropagation();},true);
  screen.addEventListener('pointermove',e=>{if(!drag)return;const box=screen.getBoundingClientRect(),x=M.clamp(drag.startX+(e.clientX-drag.x)/box.width*100,0,100),y=M.clamp(drag.startY+(e.clientY-drag.y)/box.height*100,0,100);if(drag.rect){drag.record.rect.x=x;drag.record.rect.y=y;drag.el.style.left=x+'%';drag.el.style.top=y+'%';}else{drag.record.x=x;drag.record.y=y;drag.el.style.left=x-11+'%';drag.el.style.bottom=100-y+'%';}});
  function finishDrag(e){if(!drag)return;if(drag.el.hasPointerCapture(e.pointerId))drag.el.releasePointerCapture(e.pointerId);drag=null;mark();preview();e.preventDefault();}
  screen.addEventListener('pointerup',finishDrag,true);screen.addEventListener('pointercancel',finishDrag,true);screen.addEventListener('click',e=>{if(dragEnabled){e.preventDefault();e.stopImmediatePropagation();}},true);
  addEventListener('pagehide',()=>previewURLs.forEach(url=>URL.revokeObjectURL(url)));
})();
