'use strict';
(()=>{
const M=PixelyGameModel,R=PixelyGameStore,A=PixelyAdmin,$=id=>document.getElementById(id),node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let starting=false;let data=PixelyGameData.defaults(),manifest,state=null,mode=new URLSearchParams(location.search).get('mode')||'new',selectedSlot=null,selectedType='manual',slotData,paused=false,auto=false,skip=false,last=performance.now(),saveChain=Promise.resolve(),statusTimer,voiceContext,lastVoice=0,sceneEpoch=0;
const prefs=()=>PixelySettings.get(),locationData=()=>data.locations.find(l=>l.id===state?.location),asset=id=>manifest?.assets?.[id],imageURL=id=>{const a=asset(id);return a?(a.preview||A.imageURL(a.path)):'';};
const T=PixelyDialogue,paging=new Map(),measureCanvas=document.createElement('canvas'),measureContext=measureCanvas.getContext('2d');
const captions=PixelyCaptions.create({screen:$('play-screen'),front:$('caption-front'),back:$('caption-back'),data:()=>data,state:()=>state,prefs,soundURL:key=>{const a=manifest?.sounds?.[key];return a?(a.preview||'/api/sound?path='+encodeURIComponent(a.path)):'';}});let choiceAuto=false;
function notify(text){$('game-status').textContent=text;clearTimeout(statusTimer);statusTimer=setTimeout(()=>$('game-status').textContent='',4000);}
function safeAction(fn){return async(...args)=>{try{await fn(...args);}catch(e){notify(e.message);}};}
function frozen(){return paused||$('game-panel').open||$('game-confirm').open||$('settings-dialog').open||document.querySelector('dialog[open]');}
function updateInputs(){const busy=!!state?.run||frozen();$('play-screen').classList.toggle('is-busy',busy);$('scene-overlay').classList.toggle('paused',!!frozen());$('monologue-layers').classList.toggle('paused',!!frozen());for(const host of [$('scene-layers-back'),$('scene-layers-front')])host.classList.toggle('paused',!!frozen());$('dialogue-auto').setAttribute('aria-pressed',String(auto));$('dialogue-skip').setAttribute('aria-pressed',String(skip));$('monologue-auto').setAttribute('aria-pressed',String(auto));$('monologue-skip').setAttribute('aria-pressed',String(skip));captions.tick(!!frozen());}
function clearPresentation(){captions.clear();if(state?.run)delete state.run.presentation;$('dialogue').hidden=true;$('choices').hidden=true;$('monologue-screen').hidden=true;$('play-screen').classList.remove('has-monologue');}
function currentLine(){if(!state)return null;const step=M.current(state);if(step?.type==='say')return step;if(step?.type==='monologue'){const p=state.run.presentation;return PixelyMonologue.lines(data.monologue.pages[p?.page||0])[p?.line||0];}return null;}
function monologueVisible(){const step=M.current(state||{});return step?.type==='monologue'||step?.type==='say'&&step.delivery==='monologue';}
function usesMonologue(line){return line?.delivery==='monologue'||M.current(state||{})?.type==='monologue'&&!line?.delivery;}
function speechRange(line,p){const font=prefs().textSize,mono=usesMonologue(line),width=mono?$('play-screen').clientWidth*data.monologue.textWidth/100-68:$('dialogue-next').clientWidth-32,height=mono?$('play-screen').clientHeight*.23-70:$('dialogue-next').clientHeight;
 const cacheKey=font+':'+Math.round(width)+':'+Math.round(height)+':'+line.text;let pages=paging.get(cacheKey);if(!pages){measureContext.font='700 '+font+'px "Book Text"';const widths=new Map();pages=T.paginate(line.text,width,Math.max(1,Math.floor(height/(font*1.65))),ch=>{if(!widths.has(ch))widths.set(ch,measureContext.measureText(ch).width);return widths.get(ch);});paging.set(cacheKey,pages);if(paging.size>20)paging.delete(paging.keys().next().value);}
 let index=pages.findIndex(r=>r.end>(p.offset||0));if(index<0)index=pages.length-1;const range=pages[index];return {...range,index,total:pages.length};}
function next(){if(!state||frozen())return;const step=M.current(state),line=currentLine(),p=state.run?.presentation;if(!line||!p)return;const range=speechRange(line,p);if(p.count<range.end){p.count=range.end;p.elapsed=0;drawSpeech(line,p);return;}if(range.end<line.text.length){p.offset=range.end;p.elapsed=0;drawSpeech(line,p);return;}state.readLines[p.key]=true;
 if(step.type==='monologue'){const lines=PixelyMonologue.lines(data.monologue.pages[p.page]);if((p.line||0)+1<lines.length){p.line=(p.line||0)+1;resetLine(p);renderMonologue();return;}if(p.page+1<data.monologue.pages.length){p.page++;p.line=0;resetLine(p);captions.clear(true);renderMonologue();return;}}clearPresentation();M.next(state);pump();}
function resetLine(p){p.count=0;p.offset=0;p.elapsed=0;p.effectElapsed=0;delete p.key;delete p.captionAudioPlayed;}
function prepareLine(line,p){const step=M.current(state),key=state.run.id+':'+state.run.index+(step.type==='monologue'?':'+p.page+':'+(p.line||0):'')+':'+line.text;if(p.key!==key){p.key=key;p.offset||=0;p.count||=0;p.elapsed||=0;p.effectElapsed||=0;p.wasRead=!!state.readLines[key];state.log.push({speaker:line.speaker||T.character(data,line)?.name||'꿈뜰이',text:line.text});state.log=state.log.slice(-300);if(line.actor){state.actors[state.location]||={};state.actors[state.location][line.actor]={...(state.actors[state.location][line.actor]||{}),emotion:line.emotion||'normal'};}}return key;}
function drawSpeech(line,p){const mono=usesMonologue(line),character=T.character(data,line),palette=T.style(character?.subtitleStyle,character?.id);$('dialogue').hidden=mono;$('monologue-next').hidden=!mono;$('monologue-screen').querySelector('.monologue-controls').hidden=!mono;$('dialogue-next').style.fontSize=prefs().textSize+'px';const range=speechRange(line,p);const text=line.text.slice(range.start,Math.floor(Math.min(p.count,range.end)));
 if(mono){$('monologue-text').textContent=text;$('monologue-speaker').textContent=line.speaker||character?.name||'꿈뜰이';$('monologue-next').style.fontSize=prefs().textSize+'px';$('monologue-next').style.top=data.monologue.textY+'%';$('monologue-next').style.width=data.monologue.textWidth+'%';$('monologue-next').classList.toggle('is-empty',!line.text);$('monologue-next').querySelector('.monologue-cue').textContent=p.count<range.end?'계속 ›':'다음 ›';}
 else{$('speaker-name').textContent=line.speaker||character?.name||'꿈뜰이';$('dialogue-text').textContent=text;$('dialogue-next').style.fontSize=prefs().textSize+'px';$('dialogue').style.setProperty('--speaker-accent',palette.accent);$('dialogue').style.setProperty('--speaker-soft',palette.soft);$('dialogue').querySelector('.next-mark').hidden=p.count<range.end;$('dialogue-page-number').textContent=range.total>1?(range.index+1)+' / '+range.total:'';}captions.sync(line,p,p.key);}

function beginOpening(){const steps=PixelyMonologue.opening(data);state.run=steps.length?{id:'prologue-opening',index:0,steps}:null;}
function drawMonologueText(){const p=state?.run?.presentation,line=currentLine();if(p&&line){prepareLine(line,p);drawSpeech(line,p);}}
function renderMonologue(){const p=state?.run?.presentation;if(!p)return;const config=data.monologue,page=config.pages[p.page||0];if(!page)return;$('monologue-screen').hidden=false;$('play-screen').classList.add('has-monologue');$('monologue-screen').style.backgroundColor=config.background;$('dialogue').hidden=true;$('choices').hidden=true;PixelyImageLayers.render({back:$('monologue-images-back'),front:$('monologue-images-front'),layers:page.layers,scope:page.id,image,asset,prefs});drawMonologueText();}

function drawDialogue(step,p){drawSpeech(step,p);}
function startEvent(id){if(frozen()||state.run)return false;const result=M.start(state,data,id);if(result)pump();return result;}
function snapshot(){return structuredClone({...state,updatedAt:Date.now(),thumbnail:locationData()?.background||'',builtin:locationData()?.builtin||'',contentRevision:manifest?.revision||'initial'});}
async function autosave(reason){if(!state||!prefs().autoSave||data.autosave?.[reason]===false||A.isEditor()||state.developerTest)return;const copy=snapshot();saveChain=saveChain.catch(()=>{}).then(()=>R.save(copy,'auto'));try{await saveChain;notify('자동 저장됨');}catch(e){notify('자동 저장 실패 · '+e.message);}}
function eventEnd(){clearPresentation();captions.clear(true);renderScene();updateInputs();void autosave('event');}
function pump(){if(!state||frozen())return;let turns=0;while(state.run&&turns++<400){const step=M.current(state);if(!step){state.run=null;break;}if(step.condition&&!M.conditions(step.condition,state)){M.next(state);continue;}
 if(step.type==='monologue'){if(!data.monologue.enabled){M.next(state);continue;}let p=state.run.presentation;if(!p||p.index!==state.run.index)p=state.run.presentation={index:state.run.index,page:step.page||0,line:step.line||0,count:0,elapsed:0,effectElapsed:0,offset:0};renderMonologue();updateInputs();return;}
 if(step.type==='say'){let p=state.run.presentation;if(!p||p.index!==state.run.index){const key=state.run.id+':'+state.run.index+':'+step.text;p=state.run.presentation={index:state.run.index,count:0,offset:0,elapsed:0,effectElapsed:0,wasRead:!!state.readLines[key]};prepareLine(step,p);if(step.actor){state.actors[state.location]||={};state.actors[state.location][step.actor]={...(state.actors[state.location][step.actor]||{}),emotion:step.emotion||'normal'};}renderScene();}drawDialogue(step,p);updateInputs();return;}
 if(step.type==='choice'){choiceAuto=auto;auto=skip=false;captions.clear(true);$('choices').replaceChildren();step.options.forEach((o,i)=>{const b=node('button',o.text);b.disabled=!!o.condition&&!M.conditions(o.condition,state);b.onclick=()=>{if(frozen())return;clearPresentation();M.choose(state,i);auto=choiceAuto;choiceAuto=false;pump();};$('choices').append(b);});$('choices').hidden=false;$('dialogue').hidden=true;updateInputs();return;}
 if(step.type==='puzzle'){auto=skip=false;openPuzzle(step.id);return;}
 if(['wait','shake','dim'].includes(step.type)){let p=state.run.presentation;if(!p||p.index!==state.run.index){p=state.run.presentation={index:state.run.index,remaining:M.clamp(step.ms,0,30000,step.type==='wait'?500:300)};if(step.type==='shake'&&prefs().motion){const strength=M.clamp(step.strength,0,10,2);$('play-screen').animate([{transform:'translateX(0)'},{transform:`translateX(${strength}px)`},{transform:`translateX(-${strength}px)`},{transform:'translateX(0)'}],{duration:p.remaining});}if(step.type==='dim'){state.dim=M.clamp(step.opacity,0,.8,.25);$('scene-effects').style.opacity=state.dim;}}updateInputs();return;}
 if(['move','world'].includes(step.type))captions.clear(true);if(step.type==='world'){if(prefs().motion)$('scene-overlay').animate([{opacity:1,background:'#fff4df'},{opacity:0}],{duration:650});M.apply(state,data,step);renderScene();showPlace();queueMicrotask(()=>autosave('move'));}
 else if(step.type==='image'){state.eventImage=step.visible===false?'':step.asset||'';renderScene();}
 else if(step.type==='sfx'){void PixelySettings.playEffect(step.id);if(prefs().motion&&step.id==='bush')$('scene-background').querySelector('.bush')?.animate([{transform:'translateX(20%) rotate(0)'},{transform:'translateX(20%) rotate(-1deg)'},{transform:'translateX(20%) rotate(1deg)'},{transform:'translateX(20%) rotate(0)'}],{duration:450});}
 else {const newlyCollected=step.type==='collect'&&!state.collections[step.id];M.apply(state,data,step);if(newlyCollected)collectionNotice(step.id);renderScene();if(['move','world'].includes(step.type))queueMicrotask(()=>autosave('move'));if(step.type==='chapter')queueMicrotask(()=>autosave('chapter'));if(step.type==='complete')queueMicrotask(()=>autosave('puzzle'));}delete state.run?.presentation;M.next(state);
 }if(!state.run)eventEnd();else if(turns>=400){state.run=null;notify('이벤트 단계가 너무 많아요');eventEnd();}}
async function voice(step,p){const settings=prefs();if(settings.textSound==='none'||performance.now()-lastVoice<95)return;lastVoice=performance.now();try{voiceContext??=new AudioContext();if(voiceContext.state==='suspended')await voiceContext.resume();if(frozen())return;const samples=PixelySounds.render(settings.textSound,step.actor||step.speaker||'player',Math.floor(p.count/3));const buffer=voiceContext.createBuffer(1,samples.length,PixelySounds.sampleRate);buffer.copyToChannel(samples,0);const source=voiceContext.createBufferSource(),gain=voiceContext.createGain();source.buffer=buffer;source.playbackRate.value=({jam:1,gak:.97,rad:.95,soo:1.03,gong:.98,duk:1.02})[step.actor]||1;gain.gain.value=PixelySettings.getVolume('text');source.connect(gain).connect(voiceContext.destination);source.start();}catch{}}
function tick(now){const delta=Math.min(100,now-last);last=now;if(state&&!frozen()){state.playMs+=delta;const step=M.current(state),p=state.run?.presentation,line=currentLine();if(line&&p){prepareLine(line,p);const range=speechRange(line,p),before=p.count;p.effectElapsed=(p.effectElapsed||0)+delta;p.count=prefs().textSpeed?Math.min(range.end,p.count+delta*prefs().textSpeed/1000):range.end;drawSpeech(line,p);if(!usesMonologue(line)&&Math.floor(p.count)>Math.floor(before)&&/[\p{L}\p{N}]/u.test(line.text.slice(Math.floor(before),Math.floor(p.count))))void voice(line,p);if(p.count>=range.end){p.elapsed=(p.elapsed||0)+delta;if(skip&&PixelySettings.canSkip(p.wasRead)){if(p.elapsed>140)next();}else if(skip){skip=false;updateInputs();}else if(auto&&p.elapsed>=prefs().autoDelay&&p.effectElapsed>=captions.minimum(line))next();}}
 else if(p?.remaining!==undefined){captions.sync(null,p,'wait');p.remaining-=delta;if(p.remaining<=0){delete state.run.presentation;M.next(state);pump();}}}captions.tick(!!frozen());requestAnimationFrame(tick);}

function image(id,cls=''){const src=imageURL(id);if(!src)return null;const i=node('img',undefined,cls);i.src=src;i.draggable=false;i.alt='';i.onerror=()=>i.remove();return i;}
function uploadedTransform(el,id){PixelyImageSlot.apply(el,asset(id)||{},PixelyImageSlot.typeFor(id||''));}
async function playerCanvas(){const outfit=state?.outfit;if(!outfit?.images?.length)return null;const WM=WardrobeModel,canvas=node('canvas');canvas.width=WM.WIDTH;canvas.height=WM.HEIGHT;canvas.className='outfit';const ctx=canvas.getContext('2d'),images=new Map(outfit.images);for(const part of [{id:'base',...outfit.state.base},...outfit.state.parts]){const blob=images.get(WM.imageKey(part.id));if(!blob||part.visible===false)continue;const bitmap=await createImageBitmap(blob),p=WM.imagePlacement(bitmap,part);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rotation);ctx.drawImage(bitmap,-p.width/2,-p.height/2,p.width,p.height);ctx.restore();bitmap.close();}return canvas;}
function renderScene(){if(!state)return;const isMonologue=monologueVisible();$('monologue-screen').hidden=!isMonologue;$('play-screen').classList.toggle('has-monologue',isMonologue);if(isMonologue){renderMonologue();updateInputs();return;}const l=locationData();PixelyImageLayers.render({back:$('scene-layers-back'),front:$('scene-layers-front'),layers:[...(l.layers||[]),...(data.eventLayers?.[state.run?.id]||[])],scope:l.id+':'+(state.run?.id||''),image,asset,prefs});const background=$('scene-background'),actors=$('scene-actors'),objects=$('scene-objects');const epoch=++sceneEpoch;background.replaceChildren();actors.replaceChildren();objects.replaceChildren();background.className='scene-background'+(l.builtin==='blank'&&!l.background?' blank':'');if(l.background){const i=image(l.background);if(i){uploadedTransform(i,l.background);background.append(i);}}else if(l.builtin==='house'){for(const name of ['sky','clouds','garden','house','stones','bush']){const i=node('img',undefined,'game-layer '+name);i.src='./assets/title/layers-oct8/'+name+'.webp';background.append(i);}}else background.append(node('p','배경 이미지 등록 전 · 테스트 공간','blank-background-note'));
 for(const actor of M.actors(state,l)){const character=data.characters.find(c=>c.id===actor.id);if(!character)continue;const b=node('button',undefined,'actor');b.dataset.actor=actor.id;b.setAttribute('aria-label',character.name+'와 대화');b.style.left=(M.clamp(actor.x,0,100,50)-11)+'%';b.style.bottom=(100-M.clamp(actor.y,0,100,90))+'%';b.style.zIndex=M.clamp(actor.z,0,50,10);b.style.transform=`scale(${M.clamp(actor.scale,10,300,100)/100}) rotate(${M.clamp(actor.rotate,-180,180,0)}deg) scaleX(${actor.flip?-1:1})`;const imageId=character.images?.[actor.emotion||'normal'],i=image(imageId);if(i){uploadedTransform(i,imageId);b.append(i);}else if(actor.id==='player'&&state.outfit?.images?.length){void playerCanvas().then(c=>{if(epoch===sceneEpoch&&c)b.append(c);});}else b.append(node('span',character.name+' · 이미지 등록 전','actor-empty'));if(M.current(state)?.actor===actor.id)b.classList.add('talking');b.append(node('span',character.name+' ▱','actor-hover'));b.onclick=()=>startEvent(character.talk);actors.append(b);}
 for(const object of l.objects||[]){if(state.objects?.[l.id]?.[object.id]?.visible===false||!M.conditions(object.condition,state))continue;const rect=M.rect(object.rect),b=node('button',undefined,'object-target'+(l.builtin==='blank'||object.placeholder?' placeholder':''));Object.assign(b.style,{left:rect.x+'%',top:rect.y+'%',width:rect.w+'%',height:rect.h+'%'});b.dataset.object=object.id;b.setAttribute('aria-label',object.name);const hint=node('span','◆','hint'),hover=node('span',({inspect:'⌕ ',talk:'▱ ',use:'☞ ',move:'➜ '})[object.kind]+object.name,'hover-name');hint.hidden=!prefs().interactionHints;b.append(hint,hover);b.onclick=()=>{if(frozen()||state.run)return;if(object.kind==='move'){void move(object.to);return;}if(M.investigate(state,data,object,state.selectedItem)){state.selectedItem=null;selectedBadge();pump();}else notify('이벤트 연결을 확인해 주세요');};objects.append(b);}
 for(const exit of l.exits||[]){if(!M.conditions(exit.condition,state))continue;const b=node('button',exit.side==='left'?'‹':'›','exit-arrow '+(exit.side==='left'?'left':'right'));b.title=exit.label||'이동';b.setAttribute('aria-label',b.title);b.onclick=()=>void move(exit.to);objects.append(b);}
 $('scene-effects').style.opacity=state.dim||0;$('scene-overlay').querySelector('.event-illustration')?.remove();const eventImage=image(state.eventImage,'event-illustration');if(eventImage){uploadedTransform(eventImage,state.eventImage);$('scene-overlay').append(eventImage);}selectedBadge();updateInputs();}
let collectionTimer;function collectionNotice(id){const entry=Object.values(manifest.catalogue?.collections||{}).flat().find(e=>e.id===id);if(!entry)return;const notice=$('collection-notice');notice.replaceChildren(node('span','✿','collection-stamp'),node('strong','새로운 기록'),node('span',entry.title||'콜렉션에 등록했어'));notice.hidden=false;clearTimeout(collectionTimer);collectionTimer=setTimeout(()=>notice.hidden=true,3500);}
function selectedBadge(){const i=data.items.find(i=>i.id===state?.selectedItem);$('selected-item').hidden=!i;$('selected-item').textContent=i?i.name+' · 사용':'';}
async function move(to){if(frozen()||state.run)return;if(!M.move(state,data,to))return;paused=true;updateInputs();const animation=prefs().motion?$('scene-overlay').animate([{background:'#fff4df00'},{background:'#fff4df'},{background:'#fff4df00'}],{duration:360}):null;renderScene();showPlace();if(animation){await new Promise(resolve=>setTimeout(resolve,360));animation.cancel();}paused=false;updateInputs();await autosave('move');const enter=locationData().enter;if(enter)startEvent(enter);}
function showPlace(){const p=$('place-name');p.textContent=locationData().name;p.style.animation='none';void p.offsetWidth;p.style.animation='';}
function panel(title,render){$('panel-title').textContent=title;$('panel-content').replaceChildren();render($('panel-content'));if(!$('game-panel').open)$('game-panel').showModal();updateInputs();}
function closePanel(completed=false){const cancelled=!completed&&$('game-panel').open&&M.cancelPuzzle(state||{});if($('game-panel').open)$('game-panel').close();updateInputs();if(cancelled)pump();}
function confirm(title,description,accept='덮어쓰기'){if($('game-confirm').open)return Promise.resolve(false);return new Promise(resolve=>{const d=$('game-confirm');$('confirm-title').textContent=title;$('confirm-description').textContent=description;$('confirm-accept').textContent=accept;let result=false;$('confirm-accept').onclick=()=>{result=true;d.close();};$('confirm-cancel').onclick=()=>d.close();d.addEventListener('close',()=>resolve(result),{once:true});d.showModal();});}
function bag(){panel('꿈뜰이의 가방',root=>{const list=node('div',undefined,'bag-items');for(const item of data.items.filter(i=>state.inventory[i.id]>0)){const b=node('button'),i=image(item.image);const slot=node('span',undefined,'bag-image-slot');slot.append(i||node('span','◇','item-placeholder'));if(i)PixelyImageSlot.apply(i,asset(item.image)||{},'item');b.append(slot,node('span',item.name+' × '+state.inventory[item.id]),node('small',item.description||''));b.onclick=()=>{state.selectedItem=item.id;selectedBadge();closePanel();};list.append(b);}root.append(list);if(!list.children.length)root.append(node('p','아직 가방에 담긴 물건이 없어'));root.append(node('p','아이템을 골라 대상에 사용 · ESC 또는 오른쪽 클릭으로 취소','small'));});}
function journal(){panel('꿈뜰이의 모험 일기',root=>{const facts=node('div',undefined,'journal-facts');facts.append(node('p','현재 챕터 · '+chapterName(state.chapter)),node('p','장소 · '+locationData().name),node('h2','지금 할 일'),node('p',state.goal||'주변 살펴보기'),node('h2','지나온 기록'));const ul=node('ul');state.completedGoals.forEach(t=>ul.append(node('li',t)));facts.append(ul,node('p','발견한 물건 '+Object.keys(state.collections).length+'개 · 조사 '+Object.values(state.investigations).reduce((a,b)=>a+b,0)+'회'));root.append(facts);});}
function log(){panel('지난 대사',root=>{const list=node('div',undefined,'dialogue-log');state.log.forEach(line=>{const a=node('article');a.append(node('strong',line.speaker),node('p',line.text));list.append(a);});root.append(list);list.lastElementChild?.scrollIntoView({block:'end'});});}
function menu(){if(!state)return;panel('꿈뜰이의 작은 나들이 수첩',root=>{const list=node('div',undefined,'panel-menu');for(const [title,fn]of [['게임 저장',()=>slotPanel('save')],['불러오기',()=>slotPanel('load')],['가방',bag],['모험 일기',journal],['콜렉션',safeAction(async()=>{if(A.isEditor()||state.developerTest)throw Error('테스트 플레이에서는 일반 기록을 변경하지 않아요');await R.suspend(snapshot(),saveChain);location.href='./collection.html?from=game';})],['설정',()=>document.querySelector('[data-action=settings]').click()],['타이틀로',safeAction(async()=>{if(await confirm('타이틀로 돌아갈까?','마지막 저장 이후 기록은 사라질 수 있어','돌아가기'))location.href='./index.html';})]]){const b=node('button',title);b.onclick=fn;list.append(b);}root.append(list);});}
function openPuzzle(id){const puzzle=data.puzzles.find(p=>p.id===id);if(!puzzle){notify('퍼즐 데이터가 없어요');state.run=null;eventEnd();return;}if(state.puzzles[id]){M.next(state);pump();return;}panel(puzzle.title,root=>{const form=node('form',undefined,'puzzle-input'),label=node('label',puzzle.question),input=node('input');input.type='text';input.required=true;input.maxLength=100;input.setAttribute('aria-label',puzzle.question);label.append(input);const status=node('p','', 'small'),button=node('button','확인');button.type='submit';form.append(label,button,status);form.onsubmit=e=>{e.preventDefault();if(input.value.trim()!==String(puzzle.answer)){status.textContent='다시 확인해 보자';return;}state.puzzles[id]=true;M.next(state);closePanel(true);if(!state.run&&puzzle.success)M.start(state,data,puzzle.success);else if(puzzle.success)state.run.steps.splice(state.run.index,0,...structuredClone(data.events[puzzle.success]||[]));void autosave('puzzle');pump();};root.append(form);});}
function chapterName(id){return manifest?.catalogue?.chapters?.find(c=>c.id===id)?.title|| (id==='prologue'?'프롤로그':'챕터');}
const duration=ms=>Math.floor(ms/3600000)+'시간 '+Math.floor(ms/60000)%60+'분';
function recordInfo(entry){if(entry.invalid)return '읽을 수 없는 기록 · 원본은 보존되어 있어요';const s=entry.state,location=data.locations.find(l=>l.id===s.location)?.name||s.location;return `${entry.type==='auto'?'자동':'수동'} · ${chapterName(s.chapter)} · ${location}\n${duration(s.playMs)} · ${new Date(entry.savedAt).toLocaleString('ko-KR')}`;}
async function readSlots(){slotData=await R.slots();for(const records of [slotData.manual,slotData.auto])for(const record of records.values()){if(record.invalid)continue;try{M.restore(record.state,data);}catch(e){record.invalid=true;record.error=e.message;}}return slotData;}
function slotButton(slot,entry){const b=node('button'),number=node('span',String(slot+1).padStart(2,'0'),'slot-number'),text=node('span');text.append(node('strong',entry?entry.invalid?'확인이 필요한 기록':'모험 기록':'빈 일기장'),node('small',entry?recordInfo(entry):'아직 나들이 기록이 없어'));if(entry&&!entry.invalid){const thumb=image(entry.state.thumbnail,'record-thumb')||(entry.state.builtin==='house'?node('img',undefined,'record-thumb'):node('span','◇','record-thumb empty'));if(thumb.tagName==='IMG'&&!thumb.src)thumb.src='./assets/title/layers-oct8/house.webp';if(thumb.tagName==='IMG'){thumb.alt='';thumb.draggable=false;}number.classList.add('with-thumb');number.append(thumb);}b.append(number,text);return b;}
function types(root,slot,change){const div=node('div',undefined,'confirm-buttons');for(const type of ['manual','auto']){const b=node('button',type==='manual'?'수동 기록':'자동 기록');b.disabled=!slotData[type].get(slot)||slotData[type].get(slot).invalid;b.setAttribute('aria-pressed',String(selectedType===type));b.onclick=()=>{selectedType=type;change();};div.append(b);}root.append(div);}
async function showSlots(){await readSlots();const continuing=mode==='continue';$('slots-title').textContent=continuing?'이어지는 나들이':'새로운 나들이';$('slots-subtitle').textContent=continuing?'일기 속 마지막 순간으로 돌아가자':'기록을 담을 일기장을 골라줘';$('slot-list').replaceChildren();for(let i=0;i<5;i++){const entry=slotData.manual.get(i)||slotData.auto.get(i),b=slotButton(i,entry);b.setAttribute('aria-pressed',String(selectedSlot===i));b.onclick=()=>{selectedSlot=i;selectedType=slotData.manual.has(i)?'manual':'auto';drawSlotDetail();document.querySelectorAll('#slot-list>button').forEach((x,j)=>x.setAttribute('aria-pressed',String(j===i)));};$('slot-list').append(b);}$('slot-start').onclick=safeAction(startSlot);drawSlotDetail();}
function drawSlotDetail(){const root=$('slot-description');root.replaceChildren();const entry=slotData?.[selectedType]?.get(selectedSlot);$('slot-title').textContent=selectedSlot===null?'초대는 받았고, 귀가는 미정!':'나들이 기록 '+String(selectedSlot+1).padStart(2,'0');if(selectedSlot!==null){if(mode==='continue'){types(root,selectedSlot,drawSlotDetail);if(entry&&!entry.invalid){const thumb=image(entry.state.thumbnail,'slot-thumb')||(entry.state.builtin==='house'?node('img',undefined,'slot-thumb'):null);if(thumb){if(!thumb.src)thumb.src='./assets/title/layers-oct8/house.webp';root.append(thumb);}root.append(node('p',recordInfo(entry)));}else root.append(node('p',entry?.invalid?'이 기록을 읽을 수 없어요 · 다른 기록을 골라 주세요 · 원본은 보존돼요':'아직 저장된 기록이 없어'));}else root.append(node('p',entry?'새 나들이를 시작하면 이 슬롯의 기록을 덮어써':'빈 일기장에 새로운 모험을 담자'));}else root.append(node('p','프롤로그의 집 앞에서 시작하는\n포인트 앤 클릭 시스템 테스트'));$('slot-start').disabled=selectedSlot===null||(mode==='continue'&&(!entry||entry.invalid));$('slot-start').textContent=mode==='continue'?'이 기록 이어하기':'새 나들이 시작';}
async function wardrobeSnapshot(){const db=await WardrobeStore.open();try{const w=await WardrobeStore.readWorkspace(db);return {state:WardrobeModel.normalize(w.state),images:[...w.images]};}finally{db.close();}}
async function startSlot(){if(starting||selectedSlot===null)return;starting=true;$('slot-start').disabled=true;document.querySelectorAll('#slot-list>button').forEach(b=>b.disabled=true);try{if(mode==='continue'){const entry=slotData[selectedType].get(selectedSlot);if(!entry||entry.invalid)return;state=M.restore(entry.state,data);await R.setActive(selectedSlot,selectedType);}else{const occupied=slotData.manual.has(selectedSlot)||slotData.auto.has(selectedSlot);if(occupied&&!await confirm('기록을 덮어쓸까?','슬롯 '+(selectedSlot+1)+'의 수동·자동 기록을 새로운 나들이로 바꿔'))return;let outfit;try{outfit=await wardrobeSnapshot();}catch(e){notify('옷장 모습을 가져오지 못했어요 · '+e.message);}state=M.create(data,selectedSlot,outfit);if(A.isEditor())state.developerTest=true;beginOpening();if(!A.isEditor())await R.newGame(snapshot(),occupied);}enterPlay();}finally{starting=false;document.querySelectorAll('#slot-list>button').forEach(b=>b.disabled=false);drawSlotDetail();}}
function enterPlay(){$('test-label').textContent=state.developerTest?'개발자 미리보기 · 저장 기록과 별도':'프롤로그 · 시스템 테스트';$('slot-screen').hidden=true;$('play-screen').hidden=false;renderScene();showPlace();pump();dispatchEvent(new Event('pixely:game-start'));}
async function slotPanel(kind){await readSlots();panel(kind==='save'?'나들이 기록 저장':'기록 불러오기',root=>{const list=node('div',undefined,'slot-list');for(let i=0;i<5;i++){const entry=slotData[kind==='save'?'manual':selectedType].get(i),b=slotButton(i,entry);if(kind==='load')b.disabled=!entry||entry.invalid;b.onclick=safeAction(async()=>{if(kind==='save'){if(A.isEditor()||state.developerTest)throw Error('개발자 테스트는 플레이 기록에 저장하지 않아요');if((slotData.manual.has(i)||slotData.auto.has(i))&&!await confirm('저장 기록을 덮어쓸까?','슬롯 '+(i+1)+'의 수동 기록이 바뀌어'))return;await saveChain.catch(()=>{});const copy=snapshot();copy.slot=i;await R.save(copy,'manual');state.slot=i;notify('수동 저장됨');closePanel();}else{if(!await confirm('기록을 불러올까?','현재 저장하지 않은 진행은 사라질 수 있어','불러오기'))return;state=M.restore(entry.state,data);await R.setActive(i,selectedType);closePanel(true);auto=skip=false;enterPlay();}});list.append(b);}if(kind==='load'){const select=node('select');select.setAttribute('aria-label','저장 종류');for(const type of ['manual','auto']){const option=node('option',type==='manual'?'수동 저장':'자동 저장');option.value=type;option.selected=type===selectedType;select.append(option);}select.onchange=()=>{selectedType=select.value;void slotPanel(kind);};root.append(select);}root.append(list);});}
$('monologue-auto').onclick=()=>{auto=!auto;skip=false;updateInputs();};$('monologue-skip').onclick=()=>{skip=!skip;auto=false;updateInputs();};$('monologue-log').onclick=log;$('monologue-next').onclick=next;$('dialogue-next').onclick=next;$('dialogue-auto').onclick=()=>{auto=!auto;skip=false;updateInputs();};$('dialogue-skip').onclick=()=>{skip=!skip;auto=false;updateInputs();};$('dialogue-log').onclick=log;$('open-bag').onclick=bag;$('open-journal').onclick=journal;$('open-menu').onclick=menu;$('panel-close').onclick=()=>closePanel();$('game-panel').addEventListener('cancel',e=>{e.preventDefault();closePanel();});$('game-panel').addEventListener('close',updateInputs);
addEventListener('keydown',e=>{if(e.repeat||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if([' ','Enter'].includes(e.key)&&e.target.closest?.('button')&&!e.target.closest?.('#dialogue-next,#monologue-next,.object-target,.actor'))return;if(e.key==='Escape'){if(state?.selectedItem&&!frozen()){state.selectedItem=null;selectedBadge();e.preventDefault();}else if(!frozen()){e.preventDefault();menu();}}else if([' ','Enter'].includes(e.key)&&state&&!frozen()&&['say','monologue'].includes(M.current(state)?.type)){e.preventDefault();next();}});
$('play-screen').addEventListener('click',e=>{if(e.button===0&&currentLine()&&!frozen()&&!e.target.closest('button,a,input,select,textarea,.play-tools,.dialogue-tools,.monologue-controls'))next();});addEventListener('resize',()=>{paging.clear();const line=currentLine();if(line&&state.run.presentation)drawSpeech(line,state.run.presentation);});
$('play-screen').addEventListener('contextmenu',e=>{e.preventDefault();if(state&&!frozen()){state.selectedItem=null;selectedBadge();}});$('play-screen').addEventListener('pointermove',e=>{if(!state?.selectedItem)return;const screen=$('play-screen'),r=screen.getBoundingClientRect(),x=(e.clientX-r.left)*screen.clientWidth/r.width,y=(e.clientY-r.top)*screen.clientHeight/r.height;$('selected-item').style.left=Math.min(screen.clientWidth-170,Math.max(0,x+15))+'px';$('selected-item').style.top=Math.min(screen.clientHeight-45,y+15)+'px';$('selected-item').style.bottom='auto';});
addEventListener('pixely:settingschange',()=>{paging.clear();renderScene();const step=M.current(state||{});if(step?.type==='say')drawDialogue(step,state.run.presentation);});
const ready=(async()=>{await A.ready;manifest=A.getPublished();if(!manifest)throw Error('사이트 콘텐츠를 불러오지 못했어요 · 연결을 확인하고 새로고침해 주세요');data=M.content(manifest?.game||data);if(mode==='chapter'&&new URLSearchParams(location.search).get('chapter')!=='prologue'){notify('이 챕터의 플레이 장면은 아직 연결되지 않았어요');mode='new';}if(mode==='resume'){const saved=await R.resume();if(saved){try{state=M.restore(saved,data);enterPlay();}catch(e){notify(e.message+' · 저장 목록에서 다른 기록을 골라 주세요');state=null;mode='continue';await showSlots();}}else{mode='continue';await showSlots();}}else await showSlots();requestAnimationFrame(tick);})();ready.catch(e=>notify(e.message));
window.PixelyGame={testStart:()=>{if(!A.isEditor())return;state=M.create(data,0);state.developerTest=true;beginOpening();enterPlay();},ready,node,notify,safeAction,previewState:(value,raw)=>{if(!A.isEditor())return;data=M.content(value.game);manifest=value;if(raw){state=M.restore(raw,data);state.developerTest=true;auto=skip=false;enterPlay();}else {state=M.create(data,0);state.developerTest=true;beginOpening();enterPlay();}},getData:()=>data,getManifest:()=>manifest,getState:()=>state,renderScene,startEvent,panel,closePanel,imageURL,asset,setContent:value=>{data=M.content(value.game);manifest=value;const p=state?.run?.presentation;if(M.current(state||{})?.type==='monologue'&&p){p.page=Math.min(p.page,data.monologue.pages.length-1);const lines=PixelyMonologue.lines(data.monologue.pages[p.page]);p.line=Math.min(p.line||0,lines.length-1);p.count=Math.min(p.count,lines[p.line].text.length);}if(state&&!data.locations.some(l=>l.id===state.location))state.location=data.start;renderScene();},testMonologue:(page,line=0)=>{if(!A.isEditor())return;if(!state)state=M.create(data,0);state.developerTest=true;clearPresentation();captions.clear(true);state.run={id:'prologue-monologue',index:0,steps:PixelyMonologue.opening(data,page,true)};if(state.run.steps[0])state.run.steps[0].line=line;auto=skip=false;enterPlay();},testDialogue:(steps,locationId,eventId)=>{if(!A.isEditor())return;if(!state)state=M.create(data,0);state.developerTest=true;clearPresentation();captions.clear(true);if(locationId&&data.locations.some(l=>l.id===locationId))state.location=locationId;state.run={id:eventId||'dialogue-preview',index:0,steps:structuredClone(steps)};auto=skip=false;enterPlay();},testScene:id=>{if(!A.isEditor()||!state)return;state.developerTest=true;state.location=id;state.run=null;clearPresentation();captions.clear(true);renderScene();showPlace();},pause:value=>{paused=value;updateInputs();}};
})();
