'use strict';
(()=>{
const clamp=(v,a,b,d)=>Number.isFinite(Number(v))?Math.min(b,Math.max(a,Number(v))):d;
const id=v=>typeof v==='string'&&/^[a-z0-9][a-z0-9_-]{0,79}$/i.test(v)&&!['constructor','prototype','__proto__'].includes(v);
const animations=['none','float','sway','breathe','drift','fade'];
function defaults(){return {enabled:true,background:'#FFF4DF',textY:65,textWidth:72,pages:[{id:'intro',name:'첫 독백',text:'',layers:[]}]};}
function content(raw){if(raw===undefined)return defaults();if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('독백 화면 설정을 확인해 주세요');const v=structuredClone(raw);if(!Array.isArray(v.pages)||!v.pages.length||v.pages.length>100)throw Error('독백 장면은 1~100개로 구성해 주세요');if(!/^#[0-9a-f]{6}$/i.test(v.background||''))throw Error('독백 배경색을 확인해 주세요');v.enabled=v.enabled!==false;v.textY=clamp(v.textY,20,85,65);v.textWidth=clamp(v.textWidth,40,90,72);const pages=new Set();for(const p of v.pages){if(!id(p.id)||pages.has(p.id))throw Error('독백 장면 ID를 확인해 주세요');pages.add(p.id);if(typeof p.text!=='string'||p.text.length>1000||typeof p.name!=='string'||p.name.length>100)throw Error('독백 내용은 1000자 이하로 적어 주세요');if(!Array.isArray(p.layers)||p.layers.length>100)throw Error('장면당 이미지 레이어는 100개까지 추가할 수 있어요');const layers=new Set();for(const l of p.layers){if(!id(l.id)||layers.has(l.id))throw Error('이미지 레이어 ID를 확인해 주세요');layers.add(l.id);if(typeof l.asset!=='string'||(l.asset&&!/^[a-z0-9][a-z0-9_:-]{0,160}$/i.test(l.asset)))throw Error('독백 이미지 연결을 확인해 주세요');if(typeof l.name!=='string'||l.name.length>100)throw Error('이미지 이름을 100자 이하로 적어 주세요');if(!animations.includes(l.animation||'none'))throw Error('이미지 움직임 종류를 확인해 주세요');l.animation||='none';l.visible=l.visible!==false;l.opacity=clamp(l.opacity,0,100,100);l.duration=clamp(l.duration,1,30,6);l.amount=clamp(l.amount,0,80,10);l.delay=clamp(l.delay,0,10,0);l.fit=l.fit==='cover'?'cover':'contain';}}return v;}
function opening(data,page=0,preview=false){const steps=[];if(data.monologue?.enabled!==false)steps.push({type:'monologue',page});if(!preview)steps.push(...structuredClone(data.events[data.opening]||[]));return steps;}
const api={defaults,content,animations,opening};if(typeof module!=='undefined'&&module.exports)module.exports=api;else window.PixelyMonologue=api;
})();
