'use strict';
(async()=>{
 const A=window.PixelyAdmin;if(!A)return;await A.ready;
 const child=new URLSearchParams(location.search).has('viewport-preview');
 if(child){document.body.classList.add('ratio-preview-page');addEventListener('message',async e=>{if(e.origin!==location.origin||e.source!==parent||!A.isEditor()||e.data?.type!=='pixely:preview-content')return;const G=window.PixelyGame,B=window.PixelyBooks;if(G){await G.ready;G.previewState(e.data.manifest,e.data.state);}else if(B){await B.ready;B.previewContent(e.data.book);}});parent.postMessage({type:'pixely:preview-ready'},location.origin);return;}
 const launch=document.createElement('button');launch.type='button';launch.className='ratio-preview-launch';launch.textContent='화면 비율 미리보기';launch.hidden=!A.isEditor();document.body.append(launch);addEventListener('pixely:developer-mode',()=>launch.hidden=!A.isEditor());
 let dialog,frame,area,info,ratio='21:9';const dimensions={'21:9':[2520,1080],'16:9':[1920,1080],'16:10':[1920,1200],'4:3':[1600,1200]};
 function layout(){if(!dialog?.open)return;const [w,h]=dimensions[ratio],scale=Math.min(area.clientWidth/w,area.clientHeight/h);frame.style.width=w+'px';frame.style.height=h+'px';frame.style.transform=`translate(-50%,-50%) scale(${scale})`;const game=frame.contentDocument?.getElementById('game-shell');info.textContent=`현재 브라우저 ${innerWidth} × ${innerHeight} · 미리보기 ${w} × ${h} · 미리보기 배율 ${scale.toFixed(2)}${game?' · 게임 배율 '+(game.clientWidth/1600).toFixed(2):''}`;}
 function send(){const G=window.PixelyGame,B=window.PixelyBooks;frame.contentWindow.postMessage({type:'pixely:preview-content',...(G?{manifest:G.getManifest(),state:G.getState()}:{book:B?.previewSnapshot()})},location.origin);layout();}
 launch.onclick=()=>{if(!A.isEditor())return;if(!dialog){dialog=document.createElement('dialog');dialog.className='ratio-preview-dialog';dialog.innerHTML='<header><h2>화면 비율 미리보기</h2><label>화면 비율 <select aria-label="미리보기 화면 비율"><option>21:9</option><option>16:9</option><option>16:10</option><option>4:3</option></select></label><button type="button" aria-label="화면 비율 미리보기 닫기">×</button></header><p role="status"></p><div class="ratio-preview-area"><iframe title="선택한 화면 비율의 실제 플레이 미리보기"></iframe></div><p class="small">편집 중인 화면을 확인하는 테스트 창이에요. 일반 플레이 기록에는 저장하지 않아요.</p>';document.body.append(dialog);frame=dialog.querySelector('iframe');area=dialog.querySelector('.ratio-preview-area');info=dialog.querySelector('[role=status]');dialog.querySelector('select').onchange=e=>{ratio=e.target.value;layout();};dialog.querySelector('button').onclick=()=>{dialog.close();frame.src='about:blank';};dialog.addEventListener('cancel',()=>frame.src='about:blank');frame.onload=layout;new ResizeObserver(layout).observe(area);}
 dialog.showModal();const url=new URL(location.href);url.searchParams.delete('edit');url.searchParams.set('viewport-preview','1');frame.src=url.pathname+url.search;layout();};
 addEventListener('message',e=>{if(e.origin===location.origin&&e.source===frame?.contentWindow&&e.data?.type==='pixely:preview-ready')send();});addEventListener('resize',layout);
})();
