"use strict";
(()=>{
const DB="pixely-dressup-store",STORE="images",STATE="pixely-dressup-editor-v1";
const labels={clothes:["상의","하의","신발","한벌"],items:["가방","모자","악세서리","기타"],face:["눈","입","표정","기타"],decor:["날개","장식","효과","기타"]};
const defaults=()=>({parts:[],base:{x:0,y:0,scale:100,rotate:0,visible:true},selected:"base",nextId:1});
let state=defaults(),activeTab="clothes",pendingFile=null,db=null,images=new Map(),urls=new Map();
try{const saved=JSON.parse(localStorage.getItem(STATE));if(saved&&Array.isArray(saved.parts))state={...defaults(),...saved}}catch{}
const $=id=>document.getElementById(id);
const clamp=(v,lo,hi)=>Math.min(hi,Math.max(lo,v));
const record=id=>id==="base"?state.base:state.parts.find(p=>p.id===id);
const imageKey=id=>id==="base"?"base":"part-"+id;
function save(){try{localStorage.setItem(STATE,JSON.stringify(state));$("save-status").textContent="변경 사항 자동 저장됨"}catch{$("save-status").textContent="브라우저 저장 공간을 확인해 주세요"}}
function connect(){return new Promise(resolve=>{if(!("indexedDB" in window)){resolve(null);return}const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>{req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null)})}
async function putImage(key,file){if(db){await new Promise((resolve,reject)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).put(file,key);t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}else{images.set(key,file)}await readImage(key)}
async function readImage(key){const image=await new Promise(resolve=>{if(!db){resolve(images.get(key)||null);return}const req=db.transaction(STORE).objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>resolve(null)});if(urls.has(key))URL.revokeObjectURL(urls.get(key));if(image instanceof Blob){urls.set(key,URL.createObjectURL(image))}else{urls.delete(key)}}
async function deleteImage(key){if(db){await new Promise(resolve=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).delete(key);t.oncomplete=resolve;t.onerror=resolve})}else{images.delete(key)}if(urls.has(key))URL.revokeObjectURL(urls.get(key));urls.delete(key)}
function renderStage(){const el=$("stage-layers");el.replaceChildren();const list=[{...state.base,id:"base"},...state.parts];let hasBase=false;for(const p of list){const url=urls.get(imageKey(p.id));if(!url||p.visible===false)continue;const img=document.createElement("img");img.className="stage-layer";img.src=url;img.alt=p.id==="base"?"꿈뜰이 베이스 이미지":p.name;const s=clamp(Number(p.scale)||100,10,300)/100;img.style.transform=`translate(calc(-50% + ${p.x||0}px),calc(-50% + ${p.y||0}px)) rotate(${p.rotate||0}deg) scale(${s})`;el.append(img);if(p.id==="base")hasBase=true}
if(!urls.has("base")){const p=document.createElement("p");p.id="empty-stage";p.className="empty-stage";p.innerHTML='✿<br>베이스 이미지를 먼저 추가해 주세요<small>PNG 등 투명 배경 이미지를 사용할 수 있어요</small>';el.prepend(p)}
$("look-status").textContent=urls.has("base")?`등록된 파츠 ${state.parts.length}개`:"베이스 이미지 미등록"}
function renderList(){const root=$("parts-list");root.replaceChildren();const arr=state.parts.filter(p=>p.type===activeTab);$("part-count").textContent=`${state.parts.length}개 등록 중`;if(!arr.length){const p=document.createElement("p");p.className="list-empty";p.textContent="아직 등록된 파츠가 없어요";root.append(p)}for(const part of arr){const btn=document.createElement("button");btn.className="part-item"+(state.selected===part.id?" active":"");btn.type="button";const thumb=document.createElement("img");thumb.alt="";if(urls.has(imageKey(part.id)))thumb.src=urls.get(imageKey(part.id));const name=document.createElement("span");name.textContent=part.name;const suffix=document.createElement("i");suffix.textContent=part.visible===false?"숨김":"✎";btn.append(thumb,name,suffix);btn.onclick=()=>{state.selected=part.id;save();render()};root.append(btn)}}
function renderEditor(){const select=$("layer-select");select.replaceChildren();for(const [id,name] of [["base","베이스 이미지"],...state.parts.map(p=>[p.id,p.name])]){const option=new Option(name,id);select.add(option)}if(!record(state.selected))state.selected="base";select.value=state.selected;const p=record(state.selected);$("adjust-target").textContent=state.selected==="base"?"베이스 이미지":p.name;document.querySelectorAll("[data-adjust]").forEach(input=>{const k=input.dataset.adjust;input.value=k==="scale"?p.scale:p[k];input.disabled=!urls.has(imageKey(state.selected));document.querySelector(`[data-value="${k}"]`).textContent=input.value+(k==="scale"?"%":k==="rotate"?"°":"")});$("layer-up").disabled=state.selected==="base"||state.parts.indexOf(p)>=state.parts.length-1;$("layer-down").disabled=state.selected==="base"||state.parts.indexOf(p)===0;$("layer-hide").disabled=!urls.has(imageKey(state.selected));$("layer-hide").textContent=p.visible===false?"이미지 표시":"이미지 숨기기";$("layer-remove").disabled=!urls.has(imageKey(state.selected))}
function render(){renderStage();renderList();renderEditor()}
function refreshSubtypes(){const subtype=$("new-subtype");subtype.replaceChildren();labels[$("new-type").value].forEach(s=>subtype.add(new Option(s,s)))}
$("new-type").onchange=refreshSubtypes;
$("new-file").onchange=()=>{pendingFile=$("new-file").files?.[0]||null;$("file-status").textContent=pendingFile?.name||"선택된 파일 없음";$("add-part").disabled=!pendingFile};
$("add-part").onclick=async()=>{if(!pendingFile)return;const id="p"+state.nextId++,type=$("new-type").value,name=$("new-name").value.trim()||$("new-subtype").value;const p={id,type,subtype:$("new-subtype").value,name,x:0,y:0,scale:100,rotate:0,visible:true};try{await putImage(imageKey(id),pendingFile);state.parts.push(p);state.selected=id;activeTab=type;$("new-name").value="";$("new-file").value="";pendingFile=null;$("file-status").textContent="선택된 파일 없음";$("add-part").disabled=true;save();render()}catch{$("file-status").textContent="이미지를 저장하지 못했어요"}};
$("base-file").onchange=async()=>{const file=$("base-file").files?.[0];if(!file)return;try{await putImage("base",file);state.selected="base";save();render()}catch{$("save-status").textContent="베이스 이미지를 저장하지 못했어요"}};
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("selected",x===b));renderList()});
$("layer-select").onchange=()=>{state.selected=$("layer-select").value;save();render()};
document.querySelectorAll("[data-adjust]").forEach(input=>input.oninput=()=>{const r=record(state.selected);r[input.dataset.adjust]=Number(input.value);document.querySelector(`[data-value="${input.dataset.adjust}"]`).textContent=input.value+(input.dataset.adjust==="scale"?"%":input.dataset.adjust==="rotate"?"°":"");renderStage();save()});
function move(dir){const i=state.parts.findIndex(p=>p.id===state.selected);const next=i+dir;if(i<0||next<0||next>=state.parts.length)return;[state.parts[i],state.parts[next]]=[state.parts[next],state.parts[i]];save();render()}
$("layer-up").onclick=()=>move(1);$("layer-down").onclick=()=>move(-1);
$("layer-hide").onclick=()=>{const p=record(state.selected);p.visible=p.visible===false;save();render()};
$("layer-remove").onclick=async()=>{const key=imageKey(state.selected);if(!urls.has(key))return;if(!confirm("선택한 이미지를 삭제할까요?"))return;await deleteImage(key);if(state.selected!=="base"){state.parts=state.parts.filter(p=>p.id!==state.selected)}state.selected="base";save();render()};
$("reset-image").onclick=()=>{const p=record(state.selected);Object.assign(p,{x:0,y:0,scale:100,rotate:0});save();render()};
$("save-look").onclick=()=>{save();$("save-status").textContent="현재 모습이 이 브라우저에 저장됐어요"};
async function init(){db=await connect();await readImage("base");for(const p of state.parts)await readImage(imageKey(p.id));render()}
refreshSubtypes();init();
})();