'use strict';
const {get,put,head}=require('@vercel/blob');
const {randomUUID,createHash}=require('node:crypto');
const S=require('../image-slot.js'),B=require('../book-model.js'),G=require('../game-model.js'),D=require('../book-data.js'),GD=require('../game-data.js');
const prefix=()=>process.env.PIXELY_CONTENT_SCOPE||(process.env.VERCEL_GIT_COMMIT_REF?.startsWith('codex/')?'books-qa':'books-main');
const jsonPath=type=>prefix()+'/'+type+'.json';
const assetPath=path=>typeof path==='string'&&new RegExp('^'+prefix()+'/images/[a-zA-Z0-9_-]+\\.(png|jpg|webp|gif)$').test(path);
const soundPath=path=>typeof path==='string'&&new RegExp('^'+prefix()+'/sounds/[a-zA-Z0-9_-]+\\.(mp3|ogg|wav|m4a)$').test(path);
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
function defaults(){return {version:2,revision:'initial',updatedAt:0,catalogue:D.catalogue(),assets:{},game:GD.defaults()};}
async function read(type){const path=jsonPath(type);for(let attempt=0;attempt<3;attempt++){let metadata;try{metadata=await head(path);}catch(e){if(e.name==='BlobNotFoundError'||/not found|does not exist/i.test(e.message))return {value:defaults(),etag:null};throw e;}const result=await get(path,{access:'private',useCache:false,headers:{'accept-encoding':'identity'}});if(!result)return {value:defaults(),etag:null};if(result.statusCode!==200)throw fail('저장된 내용을 읽지 못했어요',503);const value=JSON.parse(await new Response(result.stream).text()),after=await head(path);if(metadata.etag===after.etag)return {value,etag:metadata.etag};}throw fail('저장 내용이 바뀌고 있어요 · 잠시 후 다시 불러와 주세요',409);}
function normalize(raw){if(!raw||JSON.stringify(raw).length>1800000)throw fail('편집 데이터가 너무 커요');const catalogue=B.catalogue(raw.catalogue),ids=new Set([...catalogue.chapters,...Object.values(catalogue.collections).flat()].map(e=>e.id));const assets={};for(const [id,a]of Object.entries(raw.assets||{})){if(!/^[a-z0-9][a-z0-9_:-]{0,160}$/i.test(id)||!assetPath(a.path))throw fail('이미지 경로를 확인해 주세요');assets[id]={path:a.path,transform:/^(scene|character|item|event):/.test(id)?G.imageTransform(a.transform):B.imageTransform(a.transform),slot:S.normalize(a.slot||{fit:[...(raw.game?.monologue?.pages||[]).flatMap(p=>p.layers||[]),...(raw.game?.locations||[]).flatMap(p=>p.layers||[]),...Object.values(raw.game?.eventLayers||{}).flat()].some(l=>l.asset===id&&l.fit==='cover')?'cover':'contain'},S.typeFor(id)),source:S.source(a.source)};}const sounds={};if(Object.keys(raw.sounds||{}).length>500)throw fail('효과음은 500개 이하로 등록해 주세요');for(const [id,a]of Object.entries(raw.sounds||{})){if(!/^sound:[a-z0-9_-]{1,100}$/i.test(id)||!soundPath(a.path))throw fail('효과음 경로를 확인해 주세요');sounds[id]={path:a.path,name:String(a.name||'효과음').slice(0,100)};}return {version:2,revision:randomUUID(),updatedAt:Date.now(),catalogue,assets,sounds,game:G.content(raw.game)};}
async function save(raw,base){const previous=await read('draft');if(previous.value.revision!==base)throw fail('다른 편집 내용이 먼저 저장됐어요 · 새로 불러온 뒤 다시 편집해 주세요',409);const value=normalize(raw);for(const path of new Set([...Object.values(value.assets),...Object.values(value.sounds)].map(a=>a.path))){const image=await head(path);if(soundPath(path)?image.size>10*1024*1024||!/^audio\/(mpeg|ogg|wav|x-wav|mp4)$/.test(image.contentType):image.size>20*1024*1024||!/^image\/(png|jpeg|webp|gif)$/.test(image.contentType))throw fail('이미지 형식 또는 크기를 확인해 주세요');}try{await put(jsonPath('draft'),JSON.stringify(value),{access:'private',allowOverwrite:!!previous.etag,addRandomSuffix:false,contentType:'application/json',...(previous.etag?{ifMatch:previous.etag}:{})});}catch(e){if((e.name==='BlobPreconditionFailedError'||e.message.includes('ETag mismatch'))||e.message.includes('already exists'))throw fail('다른 편집과 충돌했어요 · 새로 불러와 주세요',409);throw e;}return value;}
async function publish(base,publishedBase){const draft=await read('draft'),old=await read('published');if(draft.value.revision!==base||old.value.revision!==publishedBase)throw fail('저장 또는 사이트 버전이 바뀌었어요 · 새로 불러와 주세요',409);if(base==='initial')throw fail('먼저 임시 저장을 해 주세요');await put(prefix()+'/history/'+randomUUID()+'.json',JSON.stringify(old.value),{access:'private',contentType:'application/json'});try{await put(jsonPath('published'),JSON.stringify(draft.value),{access:'private',allowOverwrite:!!old.etag,addRandomSuffix:false,contentType:'application/json',...(old.etag?{ifMatch:old.etag}:{})});}catch(e){if((e.name==='BlobPreconditionFailedError'||e.message.includes('ETag mismatch')))throw fail('사이트 반영 중 다른 변경이 생겼어요',409);throw e;}return draft.value;}
async function rateLimit(req){const ip=req.headers['x-vercel-forwarded-for']||req.socket?.remoteAddress||'unknown',path=prefix()+'/rate/'+createHash('sha256').update(String(ip)).digest('hex')+'.json';for(let i=0;i<4;i++){let metadata=null;try{metadata=await head(path);}catch(e){if(!/not found|does not exist/i.test(e.message))throw e;}const result=metadata&&await get(path,{access:'private',useCache:false,headers:{'accept-encoding':'identity'}});let state=result?JSON.parse(await new Response(result.stream).text()):{time:Date.now(),count:0};if(Date.now()-state.time>300000)state={time:Date.now(),count:0};if(state.count>=8)throw fail('잠시 후 다시 로그인해 주세요',429);state.count++;try{await put(path,JSON.stringify(state),{access:'private',allowOverwrite:!!metadata,addRandomSuffix:false,contentType:'application/json',...(metadata?{ifMatch:metadata.etag}:{})});return;}catch(e){if(i===3)throw fail('잠시 후 다시 시도해 주세요',429);}}}
module.exports={defaults,read,normalize,save,publish,rateLimit,assetPath,soundPath,prefix,fail};
